### ISSUE TITLE
Make interaction.id a bigint

### ISSUE THREAD

**Issue by lumap** [discordeno/discordeno#1036]
so you guys don't forget :)

**Comment by Skillz4Killz** [comment]
@itohatweb just making sure was this done we should do this change breaking for v12

**Comment by lumap** [comment]
no changes after more than a month, and it's still a string as i can see. might make a pr to make this a reality

**Comment by itohatweb** [comment]
Currently I have not found any solution I am satisfied with. That's why this is still open.

**Comment by lumap** [comment]
is it the same problem with interaction.guildId being a string?

**Comment by itohatweb** [comment]
yes

**Comment by lts372005** [comment]
interactiom.id in v12 is still string and not bigint
other sutff, like for example `(await getOriginalInteractionResponse(interaction.token)).id` return bigint, so please make interaction.id bigint

**Comment by itohatweb** [comment]
It's still qhat I have said above

**Comment by lts372005** [comment]
can't you just make the interaction.id bigint using `snowflakeToBigint()` ?

**Comment by itohatweb** [comment]
No I don't like this. Thats why its not like that.

**Comment by Skillz4Killz** [comment]
This has been solved, and will be deployed in next major update as this fix/change was a breaking update

**Comment by lumap** [comment]
3 months to the day :) glad it’s finally there tho
