### ISSUE TITLE
Cannot clear embeds in the other member's message

### ISSUE THREAD

**Issue by aiotter** [discordeno/discordeno#1074]
https://github.com/discordeno/discordeno/blob/d75e0549d7c2c707eb4c2a9aa5feb0c1ec55f43c/src/helpers/messages/edit_message.ts#L18-L20

This prevent clearing embeds from the other member's message, while it is possible.

**Comment by aiotter** [comment]
Removing this part will solve the problem, but I'm not sure it's the best way. That's why I created the issue before PR.
Should we preserve the system to prevent a request to edit someone's message?

**Comment by itohatweb** [comment]
No this part won't be removed only modified a bit

**Comment by aiotter** [comment]
How about this one thou
```ts
 if (message.authorId !== botId && content?.flags !== MessageFlags.SuppressEmbed) { 
   throw new Error("You can only edit a message that was sent by the bot."); 
 }
```

**Comment by itohatweb** [comment]
no not 100% what I want

**Comment by aiotter** [comment]
OK I look forward to your commit

**Comment by itohatweb** [comment]
Made this pending since there are problems with testing it.

**Comment by Skillz4Killz** [comment]
Fixed, will be deployed in upcoming update release.
