### ISSUE TITLE
types: incorrect requiredStructureProperties.members type

### ISSUE THREAD

**Issue by ayntee** [discordeno/discordeno#1076]
The "guilds" property (`GuildMemberWithUser#guilds`) does not exist on value of the`cache.requiredStructureProperties.members` Set.
![image](https://user-images.githubusercontent.com/83537790/125116786-46daee00-e0fe-11eb-94f5-c5e6d27b4ea9.png)
However, when the guilds (non-existent, according to the types) is omitted, that is, not specified in the `cache.requiredStructureProperties.members` Set, the following error is returned:
![image](https://user-images.githubusercontent.com/83537790/125116898-75f15f80-e0fe-11eb-965f-de540b47deed.png)
Though, the guilds property is handled internally by createDiscordenoMember() function: https://deno.land/x/discordeno@12.0.0/src/structures/member.ts#L172

**Comment by itohatweb** [comment]
Internally already discussed I think? For now we need to think about a good fix for this. Actually its a much bigger issue.

**Comment by itohatweb** [comment]
this bug is not fixed
