### ISSUE TITLE
 Fix permission checks for Thread typed channels

### ISSUE THREAD

**Issue by Yaikava** [discordeno/discordeno#1087]
Requested by ITOH on Discord.
![image](https://user-images.githubusercontent.com/83710104/127567221-abffc829-412a-4ff0-9f25-ad3c358ead52.png)

**Comment by Skillz4Killz** [comment]
@itohatweb Any idea what this was about? What check is not proper?

**Comment by Skillz4Killz** [comment]
@itohatweb Example error for this also plz
