### ISSUE TITLE
Interaction types vs Method types

### ISSUE THREAD

**Issue by kyeotic** [discordeno/discordeno#1102]
I'm struggling with the existing types around `Interactions` and the data-fetching methods. There are several examples, but the most common for me is guild members

An interaction, like a slash command, comes with a [`member: InteractionGuildMember`](https://github.com/discordeno/discordeno/blob/a454eb721082e6c7dc149be3793df578a383c736/src/types/interactions/interaction_guild_member.ts#L4), which (after some drilling down) has the following struct

```ts
export interface GuildMember {
  /** The user this guild member represents */
  user?: User;
  /** This users guild nickname */
  nick?: string | null;
  /** Array of role object ids */
  roles: string[];
  /** When the user joined the guild */
  joinedAt: string;
  /** When the user started boosing the guild */
  premiumSince?: string | null;
  /** Whether the user is deafened in voice channels */
  deaf: boolean;
  /** Whether the user is muted in voice channels */
  mute: boolean;
  /** Whether the user has not yet passed the guild's Membership Screening requirements */
  pending?: boolean;
}
```

An interaction with an option for `type: User` hits the backend with just the value of the User's ID. The only thing I can do (I think) to get data on this guild member is to call [`getMember`](https://github.com/discordeno/discordeno/blob/5943c8802708797f7907dbb34284381c67ae20af/src/helpers/members/get_member.ts#L11) which returns a [`DiscordenoMember`](https://github.com/discordeno/discordeno/blob/5b9de6a449/src/structures/member.ts#L202) which has the following props

```ts
export interface DiscordenoMember extends Omit<User, "discriminator" | "id" | "avatar"> {
  /** The user's id */
  id: bigint;
  /** The user's 4-digit discord-tag */
  discriminator: number;
  /** The avatar in bigint format. */
  avatar: bigint;
  /** The guild related data mapped by guild id */
  guilds: Collection<
    bigint,
    Omit<GuildMember, "joinedAt" | "premiumSince" | "roles"> & {
      joinedAt?: number;
      premiumSince?: number;
      roles: bigint[];
    }
  >;
  /** Holds all the boolean toggles. */
  bitfield: bigint;
  /** When the member has been cached the last time. */
  cachedAt: number;

  // GETTERS
  /** The avatar url using the default format and size. */
  avatarURL: string;
  /** The mention string for this member */
  mention: string;
  /** The username#discriminator tag for this member */
  tag: string;
  /** Whether or not the avatar is animated. */
  animatedAvatar: boolean;
// methods ommited
}
```

The overlap of these two types, which both refer to Guild Members, is zero. There are no properties in common at all. This makes writing functions that handle guild members quite difficult.

I think what we need is the ability to `getGuildMember` or `getInteractionGuildMember`, which could return the same type of Guild Member that Interactions receive.

**Comment by itohatweb** [comment]
What you are looking at are the values the uswr has chosen for thw options. To access these you have the interaction.data.resolved prop. in this object there is everything.

**Comment by kyeotic** [comment]
> What you are looking at are the values the uswr has chosen for thw options. To access these you have the interaction.data.resolved prop. in this object there is everything.

That's handy to know, but it doesn't really address the issue that these types refer to the same conceptual entity while having no shared properties or access patterns.

**Comment by itohatweb** [comment]
I think you are confusing GuildMember and DiscordenoMember. These are two completely different things. 
GuildMember is that what is being send when you receive an interaction. 
DiscordenoMember is a structure which is used to make it easier for you to use properties.
To create a DiscordenoMember you can do `structures.createDiscordenoMember(member, guildId)` note that you cannot do this with interaction GuildMembers because they are missing a few properties.

**Comment by kyeotic** [comment]
Yes, I am confusing them, because they both refer to the same conceptual entity: a member of a guild. They are not "completely different things", they are both "member of a guild". They have similar names, refer to the same conceptual entity, and yet have completely different properties. That's confusing. That's the issue.

I don't see your explanation documented anywhere. The documentation is really just a list of the properties though, very few of the interfaces/types have any explanation. It would help my confusion if the documentation contained your explanation, but I think a better solution would be to get rid of the core issue.

If `DiscorddenoMember` exists to make access easier then why is it missing all of the properties from `GuildMember`? Why not contain them, or have `GuildMember` as a property? It doesn't make anything easier when the interaction comes in with a `GuildMember` but the function to fetch members returns `DiscorddenoMember`, which offers _no way to compare the two_.

**Comment by itohatweb** [comment]
GuildMember and DiscordenoMember are not the same. 
If we forget about all getters and methods DiscordenoMember is actually just a Discord USER with an aditional guilds property. in this guilds property GuildMembers are being stored.

This is due to cache optimizations. 

DiscordenoMember is just our way to call it.

**Comment by kyeotic** [comment]
That's a confusing name then. "Member" seems to be consistently attached to "GuildMember", and "User" is the unattached entity. Shouldn't it be `DiscorddenoUser` if it's not a Guild Member? Again, explanations in the type/interface documentation would help confusion.

Is there are way to fetch guild members directly, instead of just fetching a user and then fetching its guilds?

**Comment by itohatweb** [comment]
There is no inbuild way to fetch a GuildMember without it being converted to a DiscordenoMember. You would have to create your own helper for that. Even though I don't understand why you would want to fetch something when everything necessary is in the interaction.data object.

**Comment by kyeotic** [comment]
> There is no inbuild way to fetch a GuildMember without it being converted to a DiscordenoMember.

I'm back to being confused. You've been saying this whole time these are different things, and that `DiscordenoMember` isn't a Guild Member. Why would a Guild Member be _converted_ into a User? That discards information! It also reinforces my confusion that they are the same conceptual entity...

I don't have any use for cache optimizations. Interactions finally provide a path to running bots on a webhook model with an ephemeral, stateless backend. Perhaps I am using the wrong tool.

**Comment by itohatweb** [comment]
So if you look at the GuildMember interface you see the user property. This one is being used to create the base of DiscordenoMember. After the remaining props of the GuildMember are added to DiscordenoMember.guilds.

**Comment by itohatweb** [comment]
If you use interaction you almost never have to fetch and GuilMember from the API. Do you mind explaining what you try to do a bit?

**Comment by kyeotic** [comment]
I'm trying to write functions that operate on these types for various purposes, like validation or metadata storage. `GuildMember` has the all the properties I need, while `DiscorddenoMember` does not. Using `DiscorddenoMember` when you actually need props from a member of a guild means relying on the cache, which I'm trying to avoid.

**Comment by itohatweb** [comment]
For DiscordenoMember you have to do following:
```ts
// The guild Member (without user prop)
const guildmem = discordenomember.guilds.get(guildId)
```
BUUT DiscordenoMember has stuff like joinedAt, premiumSince parsed as UNIX timestamps while GuildMember does not. Also roleIds is an array of bigints while for GuildMember its an array of strings

**Comment by kyeotic** [comment]
That relies on it being cached though, which is not a given in all cases. If it's not in the cache it won't show up, which could be interpreted as the user not being in the guild.

**Comment by itohatweb** [comment]
if you fetch from the Discord API it will always be in there. unless the user is really not in the guild

**Comment by kyeotic** [comment]
That essentially requires children to keep track of their parents. How should a method that receives a `DiscorddenoMember` know if it was fetched from the API or came from some other source that didn't cache the specific guild being looked at? It can't, realistically. It can't know if `guids.get()` is returning empty because the user isn't in the guild or because the parent object came from the wrong place to cache the request.

The only safe thing to do is use a type that is safe under all circumstances, and that is not the case for `DiscorddenoMember`. It is the case for `GuildMember`, so that seems like the better choice to write functions against, but the only way to get it returns it without the `user` prop.

There doesn't seem to be a good answer here.

**Comment by itohatweb** [comment]
OO I think I understand now. There are two necessary props for you in interaction.data and these are `users` and `members`. The members do not have `user` property. So you have to get the user data out of interaction.data.users[userid] and the guildmember out of interaction.data.members[userid]

**Comment by Skillz4Killz** [comment]
@kyeotic This should be fixed already in our FP rewrite branch. This fix required a breaking change so it took a while, apologies for the painful experience. I hope to improve this a lot. If you can help test this for us in the fp branch and tell me if you see any spots that I may have still missed then we can improve them but i have fixed these in as many places i could find so i am going to close this issue for now. Hit me up if you need anything fixed that i may have missed

**Comment by kyeotic** [comment]
@Skillz4Killz I would love to test this out for you. Is there a migration guide or docs for the FP branch? I'm assuming you are referring to `fp-attempt-9001`. The README links still point to the docs for main.
