### ISSUE TITLE
Add types/etc for file attachments in sendInteractionResponse fn

### ISSUE THREAD

**Issue by Yaikava** [discordeno/discordeno#1104]
Working code example
```ts
await sendInteractionResponse(ctx.interaction.id, ctx.interaction.token, {
              type: DiscordInteractionResponseTypes.ChannelMessageWithSource,
              data: {
                embeds: [embed],
              },
              //@ts-ignore 1337
              file: {
                blob: image,
                name: fileName,
              },
            });
```

It is missing in the discord docs for some reason currently. For more info check this discussion.
[https://github.com/discord/discord-api-docs/discussions/3799#discussioncomment-1302768](https://github.com/discord/discord-api-docs/discussions/3799#discussioncomment-1302768)

Thank you

**Comment by Skillz4Killz** [comment]
Should be fixed and deployed in next update
