### ISSUE TITLE
[Docs] Add a Guide On Github

### ISSUE THREAD

**Issue by Skillz4Killz** [discordeno/Discordeno#121]
**Is your feature request related to a problem? Please describe.**
The current guide requires that the user have knowledge and understanding of Github but not all users do. It would be nice to have a page dedicated to teaching end users about github.

**Describe the solution you'd like**
- What is Github?
- Create An Account on Github
- Create An Issue on Discordeno Repo
- Create A Pull Request On Discordeno Repo

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by ayntee** [comment]
Merged into #211
