### ISSUE TITLE
[Docs] Add A Guide On Git Installation/Usage

### ISSUE THREAD

**Issue by Skillz4Killz** [discordeno/Discordeno#122]
**Is your feature request related to a problem? Please describe.**
Our current step by step guide, assumes that the end user has an understanding of git and has git installed but a lot of devs are first time devs when making bots. It is important to have a section where we show how to setup git.

**Describe the solution you'd like**
- What is Git?
- Installing Git
- Cloning **Your** Discordeno Boilerplate repo

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by trylinka** [comment]
Hey!
Could I help to create docs for git installation or usage?

**Comment by chroventer** [comment]
@trylinka, feel free to

**Comment by trylinka** [comment]
@chroventer, thanks!

**Comment by ayntee** [comment]
Merged into #211
