### ISSUE TITLE
[Docs] Add A Guide on Visual Studio Code

### ISSUE THREAD

**Issue by Skillz4Killz** [discordeno/Discordeno#123]
**Is your feature request related to a problem? Please describe.**
Our current guide assumes that the user has an understanding and has already installed and setup VSC. However, a lot of bot developers are just starting to want to learn and this would be a useful part of the guide.

**Describe the solution you'd like**
- What is VSC?
- Installing VSC
- Opening VSC
- Opening A Terminal
- Moving To A Folder

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by chroventer** [comment]
Instead of creating a guide about the entire environment setup, we can have a getting started page which would have curated redirect links to installation page for Deno, setting up a project (Visual Studio Code Docs), etc.
What are your thoughts on it?

**Comment by Skillz4Killz** [comment]
That is a great idea but ideally id also like to see links to youtube tutorials on them in that case of how to set each thing up. A lot of developers that makes bots are doing this for the first time, seeing it in detail whether written on a guide or just watching a youtube video installing and setting it up would be perfect solution.

**Comment by chroventer** [comment]
On it!

**Comment by Suyashtnt** [comment]
Ive added this exact thing in my docs for discordeno helper, I'll make a PR that adds it to this docs

**Comment by ayntee** [comment]
Merged into #211
