### ISSUE TITLE
[api-docs] [Gateway] Guild member joined at can be null

### ISSUE THREAD

**Issue by Skillz4Killz** [discordeno/discordeno#1474]
A new commit was made into the api-docs repo. This issue was created automatically. Need to review if we made any change to the library for this commit.
https://github.com/discord/discord-api-docs/commit/518cd57d28d44f13a662e6ac4116d67e7ede3671

**Comment by itohatweb** [comment]
WHAT now

**Comment by Skillz4Killz** [comment]
Done
