### ISSUE TITLE
Voice Functionality

### ISSUE THREAD

**Issue by Skillz4Killz** [discordeno/discordeno#16]
**Is your feature request related to a problem? Please describe.**
The library needs voice functionality for stuff like music bots.

**Describe the solution you'd like**
Need to research about voice functionality.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by TTtie** [comment]
Deno supports UDP under an unstable API: https://doc.deno.land/https/raw.githubusercontent.com/denoland/deno/master/cli/js/lib.deno.unstable.d.ts#Deno.listenDatagram

**Comment by Skillz4Killz** [comment]
Thank you TTie ill look into that tonight

**Comment by ayntee** [comment]
The API is still unstable. This will not be implemented just yet.

Deno#listenDatagram: <https://doc.deno.land/builtin/unstable#Deno.listenDatagram>

**Comment by Mar0xy** [comment]
I will wait for the release of Voice Functionality since my bot relies on it heavily and I think most bots actually need some kind of voice functionality but I also just don't see the listenDatagram API going into the stable release until atleast 3-5 more months.

**Comment by Skillz4Killz** [comment]
After doing a bit of research I believe i've come up with a pretty neat idea on how to support voice in DD.

1. User types command to trigger bot to join voice
2. Bot contacts gateway to get details for voice channel
3. Bot runs a function(controller) something thats overridable by tht euser
4. This function triggers the udp ws handling

Step 3 is extremely important. THis will allow advanced users to plug in and basically create a separate process for there voice connections. For example

`ENV ARGS HERE pm2 start voicemod.ts "interpreter"="deno" .......`

This means they could basically keept their voice stuff going and never stop nor be effected by their bot's process. Even if the bot crashes or it needs to restart or anythign their voice connections never stop. We just need to somehow continue using controllers in other parts so it allows advanced communication between processes like if its needed to pause or resume to stop or skip etc

**Comment by ayntee** [comment]
This issue is merged in #193.

**Comment by Skillz4Killz** [comment]
Already works with lavadeno
