### ISSUE TITLE
[api-docs] Modify guild channel positions does not require swapping(

### ISSUE THREAD

**Issue by Skillz4Killz** [discordeno/discordeno#1666]
A new commit was made into the api-docs repo. This issue was created automatically. Need to review if we made any change to the library for this commit.
https://github.com/discord/discord-api-docs/commit/05691a3bf2fd1b8e6c4ddc1f1e0270f01283a857

**Comment by Yaikava** [comment]
Do not think this needs any changes.

**Comment by Skillz4Killz** [comment]
Done
