### ISSUE TITLE
[api-docs] Document Guild Scheduled Event structure and HTTP methods (#3586) Add guild scheduled events endpoints, gateway events, audit log, invite,and permissions changes.

### ISSUE THREAD

**Issue by itohatweb** [discordeno/discordeno#1789]
A new commit was made into the api-docs repo.
https://github.com/discord/discord-api-docs/commit/1298152172d3359abf069d1b24d4bbc85532b735

This is a bot created issue.

**Comment by Skillz4Killz** [comment]
Working on this

**Comment by Skillz4Killz** [comment]
Done, only unit tests remain pending to see if discord will support letting bots create them in small servers
