### ISSUE TITLE
createSlashCommand shall not take type property

### ISSUE THREAD

**Issue by itohatweb** [discordeno/discordeno#1796]
createSlashCommand shall not take type property. It shall always create ChatInput commands.

**Comment by Skillz4Killz** [comment]
why?

**Comment by lts20050703** [comment]
because createSlashCommand shall create ApplicationCommand/SlashCommand and not ApplicationCommand/USER nor ApplicationCommand/MESSAGE ?

**Comment by itohatweb** [comment]
indeed

**Comment by itohatweb** [comment]
or change the name

**Comment by Skillz4Killz** [comment]
Already was changed in the commit that closed the issue. Reclosing. If you think i missed something plz let me know where it was i missed it

**Comment by itohatweb** [comment]
I always miss pushes to main .-.
