### ISSUE TITLE
Discordeno CLI

### ISSUE THREAD

**Issue by Skillz4Killz** [discordeno/discordeno#1805]
If anyone is interested in helping lead the development of our CI please reach out. We are hoping to make a very powerful CI that can help setting up projects with discordeno extremely easy.

**Comment by lts20050703** [comment]
CI or CLI?

**Comment by itohatweb** [comment]
CLI.

PS: Skillz we already have some kind of code for it here https://github.com/discordeno/cli (Private atm)

**Comment by Skillz4Killz** [comment]
@itohatweb Yea good catch i had no idea. However, I would still like someone to take lead of that project and build it. I would give them full control over the idea and design it as they wish in that repo. Sadly I don't have the time but i feel like a CI is an incredibly useful tool. I would love to use it to support community frameworks and such. For example:

create-discordeno-bot

1. Hey there 👋 thanks for using discordeno. To proceed you should first choose which type of bot you would like. Details for each choice can be seen here: insert url here

A) Gateway Bot
B) HTTP Bot

2. A Gateway Bot. Great choice. Now let's get you started. Do you prefer class based code(OOP heavy) or a more functional approach? 

3. Class based it is! There are x frameworks to choose from that make it possible to use Discordeno using Classes. Which would you like to use?

A) Natico
B) Amethyst

etc....

Once the picks are done, an entire repo is basically prepared for them based on their selections and a lot more steps can be added here as well to fine tune for example custom cache, separate gateway, separate rest etc....

**Comment by itohatweb** [comment]
It's a great idea but stuff like this gets highly complex and complicated. Also us having an entire repo for all possible selections could lead us to have thousands of repos to maintain.

**Comment by lts20050703** [comment]
It's been a month
Have you two agreed on whether or not making a Discordeno CLI?

**Comment by Skillz4Killz** [comment]
The CLI could be useful but it's not a priority since we have the template repo. This is something more so meant for the community. If someone wants to make a CLI they can.

**Comment by lts20050703** [comment]
> CLI.
> 
> PS: Skillz we already have some kind of code for it here https://github.com/discordeno/cli (Private atm)

If so is it possible for you guys to public it so someone can contribute to it?-

**Comment by itohatweb** [comment]
Nah, it's licensed under ayntee

**Comment by Skillz4Killz** [comment]
Already added to readme. Great stuff from reboot so far. Keep it up! Make it a great CLI!
