### ISSUE TITLE
[api-docs] fix: remove duplicate error code (#4122)

### ISSUE THREAD

**Issue by itohatweb** [discordeno/discordeno#1807]
A new commit was made into the api-docs repo.
https://github.com/discord/discord-api-docs/commit/ce42fdd223c310bcec8067fa0cd703d9c5964f31

This is a bot created issue.

**Comment by lts20050703** [comment]
discordeno doesn't have a duplicate error code in [/src/types/codes/jsonErrorCodes.ts](https://github.com/discordeno/discordeno/tree/main/src/types/codes/jsonErrorCodes.ts)
