### ISSUE TITLE
Research which endpoints do not require a bot token

### ISSUE THREAD

**Issue by Skillz4Killz** [discordeno/discordeno#1814]
We should make an option to remove the bot token from the header if in certain endpoints that odnt require a bot token

https://github.com/discord/discord-api-docs/issues/4142

**Comment by Skillz4Killz** [comment]
This was stated as a bug by discord devs and should not require lib changes.

**Comment by Skillz4Killz** [comment]
Re-opening because a discord staffer has made this change in their lib, so it might not be considered a bug anymore and needs to be fixed now in our lib

https://github.com/twilight-rs/twilight/pull/1317

**Comment by lts20050703** [comment]
how do we research exactly? like reading <https://discord.dev>?

**Comment by lts20050703** [comment]
For authorization, all endpoints take either a bot token or client credentials token for your application
https://discord.com/developers/docs/interactions/application-commands#endpoints
https://discord.com/developers/docs/interactions/receiving-and-responding#endpoints
Am I understanding the docs correctly?

**Comment by itohatweb** [comment]
Endpoints related to for example Webhooks and Interactions do not require an Authorization header.

**Comment by Skillz4Killz** [comment]
Staff confirmed once again this is a bug and should not need changes in a lib. This is something they will fix soon
