### ISSUE TITLE
editStageInstance and createStageInstance should use a transformer

### ISSUE THREAD

**Issue by Skillz4Killz** [discordeno/discordeno#1815]
Currently we return raw objects, but it would be nicer to have them use a transformer. DRY!

**Comment by lts20050703** [comment]
uhh what transformer to use? I can't seem to find any stage instance transformer
also I don't see editStageInstance.ts in [src/helpers/channels](https://github.com/discordeno/discordeno/tree/main/src/helpers/channels)

**Comment by Skillz4Killz** [comment]
yea the idea is to make a transformer for them. It may be called updateStageInstance

**Comment by lts20050703** [comment]
#1863
