### ISSUE TITLE
[api-docs] update change log for guild_scheduled_events field addition (#4149)

update change log and very minor rewording

### ISSUE THREAD

**Issue by itohatweb** [discordeno/discordeno#1818]
A new commit was made into the api-docs repo.
https://github.com/discord/discord-api-docs/commit/e230f408d0777209d3163e9bd640e89aa3cea3a9

This is a bot created issue.

**Comment by lts20050703** [comment]
uhh this is just discord updating its changelog
I think we can close this (if we didn't forgot to add `guild_scheduled_events` field on `Guild` resource sent with `GUILD_CREATE` event)
