### ISSUE TITLE
[GH Action] Add Copy Configs File Step To Pull Request Workflow

### ISSUE THREAD

**Issue by Skillz4Killz** [discordeno/discordeno#1823]
**Describe the bug** A clear and concise description of what the bug is.
Currently the GH action that runs tests on pull requests is breaking. This is because the tests depend on a configs.ts file which is not generated during this test. 

**To Reproduce** Steps to reproduce the behavior:

Type run-tests on any pr.

**Expected behavior** A clear and concise description of what you expected to
happen.

The test should run.

The solution is simple. Just copy the 2 lines from the main tests.yml

**Comment by lts20050703** [comment]
#1825
