### ISSUE TITLE
[api-docs] Document guild_scheduled_events field on audit log object (#4152)

Add guild_scheduled_events field on audit log object

### ISSUE THREAD

**Issue by itohatweb** [discordeno/discordeno#1828]
A new commit was made into the api-docs repo.
https://github.com/discord/discord-api-docs/commit/a80c210df2fba79ab95458d82f68633db7aaead6

This is a bot created issue.

**Comment by lts20050703** [comment]
#1854

**Comment by lts20050703** [comment]
@Skillz4Killz I think you forgot to close this issue?
