### ISSUE TITLE
[api-docs] Update Guild Preview (#4191)

* Update Guild Preview

Public stages no longer make guilds "previewable"

* Update docs/resources/Guild.md

Co-authored-by: Vitor <milagre.vitor@gmail.com>

Co-authored-by: Vitor <milagre.vitor@gmail.com>

### ISSUE THREAD

**Issue by itohatweb** [discordeno/discordeno#1837]
A new commit was made into the api-docs repo.
https://github.com/discord/discord-api-docs/commit/409c5c7dcd0556bf82d317307715c03aaa5e6cdb

This is a bot created issue.

**Comment by lts20050703** [comment]
as far as I understand, it's just discord docs update
Do we need to update anything?
