### ISSUE TITLE
[api-docs] Update scheduled events documentation (#4216)

- Remove confusing gateway events statement
- Document upcoming changes for event visibility for lurkers
- Cleanup time sensitive warnings and caveats that are no longer necessary

### ISSUE THREAD

**Issue by itohatweb** [discordeno/discordeno#1840]
A new commit was made into the api-docs repo.
https://github.com/discord/discord-api-docs/commit/c081c1f08f28ce8ab031aba1cfdc82e7213b3f00

This is a bot created issue.

**Comment by lts20050703** [comment]
Do we actually have to update anything?
