### ISSUE TITLE
[api-docs] Document audit logs for scheduled events (#4237)

### ISSUE THREAD

**Issue by itohatweb** [discordeno/discordeno#1848]
A new commit was made into the api-docs repo.
https://github.com/discord/discord-api-docs/commit/37a25dd805cdb9ba86002149faeb451e5d426f95

This is a bot created issue.

**Comment by lts20050703** [comment]
> info
> This endpoint supports the `X-Audit-Log-Reason` header.
Do we need to change anything?

**Comment by Skillz4Killz** [comment]
Yea it just means these endpoints can accept a `reason` option now

**Comment by lts20050703** [comment]
# #1869
