### ISSUE TITLE
[api-docs] remove scheduled events gateway events experimental disclaimer (#4238)

remove experimental disclaimer for gateway events which are stable and supported

### ISSUE THREAD

**Issue by itohatweb** [discordeno/discordeno#1849]
A new commit was made into the api-docs repo.
https://github.com/discord/discord-api-docs/commit/425d3ef6d1c004906e93ac6b6482fb230e0e2256

This is a bot created issue.

**Comment by lts20050703** [comment]
If I understand correctly it's just discord remove disclaimer
