### ISSUE TITLE
[api-docs] Denotes sticker_pack.banner_asset_id as optional (#4245)

### ISSUE THREAD

**Issue by itohatweb** [discordeno/discordeno#1851]
A new commit was made into the api-docs repo.
https://github.com/discord/discord-api-docs/commit/b24e9e75b033b15f748f92ec9ec92cbae84981b7

This is a bot created issue.

**Comment by lts20050703** [comment]
I can't seem to find `sticker_pack` anywhere... Where is it?

**Comment by lts20050703** [comment]
<https://discord.com/developers/docs/resources/sticker>
I found sticker object in [/src/types/message/messageSticker.ts](https://github.com/discordeno/discordeno/blob/main/src/types/messages/messageSticker.ts), sticker format type in [/src/types/message/messageStickerFormatTypes](https://github.com/discordeno/discordeno/blob/main/src/types/messages/messageStickerFormatTypes.ts), and sticker item in [/src/types/message/messageStickerItem](https://github.com/discordeno/discordeno/blob/main/src/types/messages/messageStickerItem.ts)
We are still missing the sticker type enum and sticker pack object.
# Consider moving stickers types to a separate folder?

**Comment by lts20050703** [comment]
#1861
