### ISSUE TITLE
[api-docs] Tweak `application_id` wording on message object (#4244)

* Tweak `application_id` wording on message object

* Update Channel.md

Co-authored-by: Ian Webster <ianw_github@ianww.com>

### ISSUE THREAD

**Issue by itohatweb** [discordeno/discordeno#1858]
A new commit was made into the api-docs repo.
https://github.com/discord/discord-api-docs/commit/46f028029697051d0897f6d03d24aad3f9e24d84

This is a bot created issue.

**Comment by lts20050703** [comment]
> application_id? | snowflake | if the message is an [Interaction](#DOCS_INTERACTIONS_RECEIVING_AND_RESPONDING/) or application-owned webhook, this is the id of the application |

discord update wording, if the message is an interaction OR it's webhook then application_id is the id of the application

**Comment by lts20050703** [comment]
#1860
