### ISSUE TITLE
[api-docs] Add reconnect column to close code table (#4261)

### ISSUE THREAD

**Issue by itohatweb** [discordeno/discordeno#1859]
A new commit was made into the api-docs repo.
https://github.com/discord/discord-api-docs/commit/77e1813458dedf4b3efd07e2d99e7d18e57a2911

This is a bot created issue.

**Comment by lts20050703** [comment]
Discord making the docs clear which opcodes you should reconnect and which opcodes you should not
Do we need to change anything about how we reconnect or not when got opcodes from discord?

**Comment by itohatweb** [comment]
Just opened to not forget to check if we really do it right

**Comment by lts20050703** [comment]
<https://discord.com/developers/docs/topics/opcodes-and-status-codes#gateway-gateway-close-event-codes>
Why I don't see the new version 🤔

**Comment by lts20050703** [comment]
> Just opened to not forget to check if we really do it right

anyways where do I need to check?

**Comment by Skillz4Killz** [comment]
Checked we good!
