### ISSUE TITLE
Finish up plugins

### ISSUE THREAD

**Issue by itohatweb** [discordeno/discordeno#1883]
- [ ] Validation plugin (#1882)
- [ ] Permission plugin
- [ ] Fileloader plugin
- [ ] Helpers plugin
- [ ] Cache plugin

**Comment by lts20050703** [comment]
Validation Plugin
#1908 
#1913 
#2094 
#2137 

Permission Plugin
#1907

**Comment by Skillz4Killz** [comment]
Please make separate issues for any plugin needing changes, like the validation one and each issue should have a detailed explanation of what needs finishing up
