### ISSUE TITLE
Improve Transformers

### ISSUE THREAD

**Issue by itohatweb** [discordeno/discordeno#1885]
- [ ] Add transformers to convert objects to a Discord payload.
- [ ] Don't use magic numbers for transformers (eg. `bitfield` in `DiscordenoRole`)
- [ ] Add deconstructors (utility) for the `bitfield`s in custom objects
- [ ] Improve transformers file structure

**Comment by Skillz4Killz** [comment]
Unless this comes with explanations of how to achieve the same user experience and such without using things like bitfields and such then this issue is just another broad issue. These are great idea but they need more details and explanations
