### ISSUE TITLE
[api-docs] Add locale fields to interaction structure (#4265)

### ISSUE THREAD

**Issue by itohatweb** [discordeno/discordeno#1894]
A new commit was made into the api-docs repo.
https://github.com/discord/discord-api-docs/commit/30cc2ea5efc83e2398c72d2a47f5aeccd5e21a84

This is a bot created issue.

**Comment by lts20050703** [comment]
@itohatweb do you want me not to create PR for this since this will likely interfere your type rewrite

**Comment by itohatweb** [comment]
Yea, since its a type addition I will add it, thanks.
