### ISSUE TITLE
[api-docs] Document behavior of CONNECT permission (#4291)

Closes #1522

### ISSUE THREAD

**Issue by itohatweb** [discordeno/discordeno#1907]
A new commit was made into the api-docs repo.
https://github.com/discord/discord-api-docs/commit/f0bb955313a4dfddb3548ea8ce74c6f82f669c43

This is a bot created issue.

**Comment by lts20050703** [comment]
> For voice and stage channels, denying the `CONNECT` permission also implicitly denies other permissions such as `MANAGE_CHANNEL`

Discord documenting Implicit Permissions, We can close this?

**Comment by lts20050703** [comment]
It's been a week.
Anyone?
