### ISSUE TITLE
[api-docs] Document filename restrictions for attachment URLs (#4292)

* Document filename restrictions for attachment URLs

Closes #2102

* Dashes are also supported

### ISSUE THREAD

**Issue by itohatweb** [discordeno/discordeno#1908]
A new commit was made into the api-docs repo.
https://github.com/discord/discord-api-docs/commit/5868a2b4f1d4e385d4c11cd27dca06fa92418111

This is a bot created issue.

**Comment by lts20050703** [comment]
> Images can also be referenced in embeds using the `attachment://filename` URL. The `filename` for these URLs must be ASCII alphanumeric with underscores, dashes, or dots. An example payload is provided below.

Discord documenting Uploading Files Reference. We can close this?

**Comment by lts20050703** [comment]
> The `filename` for these URLs must be ASCII alphanumeric with underscores, dashes, or dots.
Discord clarify filename rules. Can we close this?
