### ISSUE TITLE
[api-docs] document message create flags (#4356)

### ISSUE THREAD

**Issue by itohatweb** [discordeno/discordeno#1910]
A new commit was made into the api-docs repo.
https://github.com/discord/discord-api-docs/commit/95816a58aec3b04798e77079dee2b271d243ecdd

This is a bot created issue.

**Comment by lts20050703** [comment]
https://discord.com/developers/docs/resources/channel#create-message-jsonform-params
https://discord.com/developers/docs/resources/webhook#execute-webhook-jsonform-params
