### ISSUE TITLE
member.communicationDisabledUntil returns a string but the type is a number

### ISSUE THREAD

**Issue by some-boi** [discordeno/discordeno#1912]
By discordeno's types member.communitionDisabledUntil is a string, but when u get the property it returns a string
 so i am guessing there's something wrong with types
![image](https://user-images.githubusercontent.com/41384430/150898793-a821c10d-93d0-4020-aa6d-2fd9c2d81edb.png)

**Comment by lts20050703** [comment]
> By discordeno's types member.communitionDisabledUntil is a string, but when u get the property it returns a string

@some-boi sorry I had a stroke reading that
Discord return ISO8601 timestamp so Discordeno return a string
Is this what you not expected?
