### ISSUE TITLE
[api-docs] clarify embed character limit (#4379)

### ISSUE THREAD

**Issue by itohatweb** [discordeno/discordeno#1913]
A new commit was made into the api-docs repo.
https://github.com/discord/discord-api-docs/commit/b3cc70e1d053464a962787e1637c10ddb4d83a0f

This is a bot created issue.

**Comment by lts20050703** [comment]
```diff
- Additionally, the characters in all `title`, `description`, `field.name`, `field.value`, `footer.text`, and `author.name` fields must not exceed 6000 characters in total. Violating any of these constraints will result in a `Bad Request` response.
+ Additionally, the combined sum of characters in all `title`, `description`, `field.name`, `field.value`, `footer.text`, and `author.name` fields across all embeds attached to a message must not exceed 6000 characters. Violating any of these constraints will result in a `Bad Request` response.
```
Discord just clarify embed character limit
We can close this?

**Comment by Skillz4Killz** [comment]
We can but we should open an issue in template repo where we have the embed class

**Comment by lts20050703** [comment]
> We can but we should open an issue in template repo where we have the embed class

@Skillz4Killz The template is now here lol

**Comment by lts20050703** [comment]
> We can but we should open an issue in template repo where we have the embed class

I have checked [template/utils/Embed.ts](https://github.com/discordeno/discordeno/blob/main/template/bigbot/src/utils/Embeds.ts)

Our implementation is correct.

<img width="245" alt="image" src="https://user-images.githubusercontent.com/87189679/153697562-03ed59ae-b1bf-466a-8ec9-22b3ab7f33a4.png">
<img width="428" alt="image" src="https://user-images.githubusercontent.com/87189679/153697568-95f56619-3d51-435a-bec5-d37d431c9e52.png">

all methods like setAuthor, setDescription, addField, etc... use fitData to make sure it's under the limit.

**Comment by lts20050703** [comment]
> We can but we should open an issue in template repo where we have the embed class

@Skillz4Killz I have checked [template/utils/Embed.ts](https://github.com/discordeno/discordeno/blob/main/template/bigbot/src/utils/Embeds.ts)

Our implementation is correct to make sure it's under the limit.

<img width="245" alt="image" src="https://user-images.githubusercontent.com/87189679/153697562-03ed59ae-b1bf-466a-8ec9-22b3ab7f33a4.png">
<img width="428" alt="image" src="https://user-images.githubusercontent.com/87189679/153697568-95f56619-3d51-435a-bec5-d37d431c9e52.png">

all methods like setAuthor, setDescription, addField, etc... use fitData to make sure it's under the limit.

**Comment by itohatweb** [comment]
This should be closed by the validation plugin
