### ISSUE TITLE
[api-docs] Document what message flags can be sent (#4357)

### ISSUE THREAD

**Issue by itohatweb** [discordeno/discordeno#1916]
A new commit was made into the api-docs repo.
https://github.com/discord/discord-api-docs/commit/1d39b02ca8dcc54d33316cc95e6eccfb8c7725cc

This is a bot created issue.

**Comment by lts20050703** [comment]
Can we close this issue in favor of #1941? Because #1941 covers both this and #1910 AND message interface in general is outdated anyways
