### ISSUE TITLE
v10

### ISSUE THREAD

**Issue by Skillz4Killz** [discordeno/discordeno#193]
- [x] Overridable handlers

```ts
export const handlers = {
    addRole: () => {},
    ...
};
```

- [ ] Separate REST to separate package. Useful when someone wants to create a web dashboard or a REST proxy(big brain bots).
- [ ] Separate WS to separate package. Useful when someone wants to create a proxy ws for big brain bots
- [x] Better error messages for HTTP
- [x] Better error messages for WebSocket
- [x] Stickers support
- [x] Switch to web WebSocket API
- [x] Change `Permissions[]` to `Permission[]` for consistency
- [x] Slash commands and interactions (#247, #248)
- [x] Better directory structure (#258)
- [ ] Implement getters (#259, #262)

**Comment by Skillz4Killz** [comment]
@ayntee Let me know ur thoughts on these and if u have any other ideas ud like to add

**Comment by ayntee** [comment]
Better error messages for request manager

**Comment by ayntee** [comment]
`Guild.roles` -> `cache.roles`

**Comment by Skillz4Killz** [comment]
Error messages i totally agree with, but guild roles are you sure? Roles are unique to each server, none of them share anything  with another role from another server. cache.members make sense because they share username, discriminator, avatar etc... cache.channels makes sense because its literally just duplicated data.

**Comment by Skillz4Killz** [comment]
Support for REST and WS proxy should be good to go but needs testing. We still have to consider if it's worth making our rest and ws an entirely separate package as well

**Comment by ayntee** [comment]
> Support for REST and WS proxy should be good to go but needs testing. We still have to consider if it's worth making our rest and ws an entirely separate package as well #161

Although, this would be a good edition to the library, this will be a major change and we should discuss this and get opinions from the users. For now, an average user may not at all need to customize ws or rest.

**Comment by Skillz4Killz** [comment]
Change all Permissions[] to Permission[] i think would also be good for users. This allows them to use the same consistent form to work with the lib as opposed to some confusion and also removes the need to have to import the permissions enum

**Comment by ayntee** [comment]
Before merging the `v10` PR, maybe we should nuke versioned branches as well.

**Comment by Skillz4Killz** [comment]
@ayntee ideally I would like to wait until Discord nukes v6 because then all those branches will stop functioning. In case anyone is using the raw github url from one of those commits/branches id like to keep it alive until discord kills v6

**Comment by userterminal** [comment]
Anything on the status of stickers support?

**Comment by Skillz4Killz** [comment]
@userterminal I wasn't aware anyone wanted stickers support so i didn't prioritize it. Will keep it in mind now that i know youd like it

That said, stickers is already available! It just doesn't have the autocompletion yet but its there on the message object in case you need it. Only thing we gotta do on the DD side, just adds the documentation for it tbh.

**Comment by userterminal** [comment]
@Skillz4Killz I don't specifically need stickers support but was just wondering if It was still being done as it was listed. Would still be nice to have to cover the full API though.

**Comment by ayntee** [comment]
> @Skillz4Killz I don't specifically need stickers support but was just wondering if It was still being done as it was listed. Would still be nice to have to cover the full API though.

Just wanted to let you know that stickers support (types) is already implemented and will be out in v10.

**Comment by userterminal** [comment]
> > @Skillz4Killz I don't specifically need stickers support but was just wondering if It was still being done as it was listed. Would still be nice to have to cover the full API though.
> 
> Just wanted to let you know that stickers support (types) is already implemented and will be out in v10.

Yeah, I ended up noticing that, thanks though.

**Comment by ayntee** [comment]
Better error messages for WebSocket close codes.
