### ISSUE TITLE
[api-docs] Document `newly_created` on the THREAD_CREATE dispatch

### ISSUE THREAD

**Issue by itohatweb** [discordeno/discordeno#1976]
A new commit was made into the api-docs repo.
https://github.com/discord/discord-api-docs/commit/1875d80011ea62bf555ce807459ccf97950291e9

This is a bot created issue.

**Comment by lts20050703** [comment]
Waiting for Discord to update <https://discord.com/developers/docs/resources/channel#thread-metadata-object-thread-metadata-structure>
