### ISSUE TITLE
(Recommendation/Idea) createSlashCommand() method

### ISSUE THREAD

**Issue by MilSci** [discordeno/discordeno#1989]
One of the troubles I've been running into a lot are slash commands, specifically creating them and using them. I think a solid idea that could be possible would be to create a new method `createSlashCommand()` instead of having a property on the `createCommand()` method; the reason being it can become quite complex or complicated which leads to confusion. I know ITOH is working on an arg parser and there is a deno-serverless-deploy repository, maybe that repo, or at least how slash commands are done there, can be added into the template.

Feel free to comment any questions or feedback (even if it's saying my idea won't work or isn't necessary)

**Comment by Skillz4Killz** [comment]
This no longer applies to the rewritten template. It no longer uses message commands and / are the only style supported so this issue although a really good point is no longer necessary.
