### ISSUE TITLE
[api-docs] document modals (#4459)

### ISSUE THREAD

**Issue by itohatweb** [discordeno/discordeno#2016]
A new commit was made into the api-docs repo: https://github.com/discord/discord-api-docs/commit/4b6c6a14d46ff2e62f6384e3ebd9116243c650c9
No details given.

This is a bot created issue.

**Comment by lts20050703** [comment]
Waiting for #2062

**Comment by Skillz4Killz** [comment]
@lts20050703 what are we waiting on i think this is already supported in dd no?
