### ISSUE TITLE
[helpers] Add userConnections

### ISSUE THREAD

**Issue by Skillz4Killz** [discordeno/discordeno#2081]
https://discord.com/developers/docs/resources/user#get-user-connections

**Comment by itohatweb** [comment]
This is an OAuth2 endpoint

**Comment by Skillz4Killz** [comment]
We should still add it itoh for users who are going to use discordeno on web. Since we now support nodejs bots who want to make dashboards may want to use discordeno so imo oauth endpoints should be available now. What do you think?

**Comment by itohatweb** [comment]
we do not support any oauth2 endpoints currently. 
if so we should add support for oauth2

**Comment by lts20050703** [comment]
~~another plugin~~

**Comment by itohatweb** [comment]
Restrained by #2133
