### ISSUE TITLE
Component transform doesn't set `value`

### ISSUE THREAD

**Issue by JasperVanEsveld** [discordeno/discordeno#2110]
Component transform does not pass the value field, used by the `InputTextComponent`.
Meaning that you can't actually use the value typed by the user.

I would make a PR to fix it, but I can't get the current main branch running because of the refactors that seem to be happening with `Optionalize`ing return types.

**Screenshots**
![image](https://user-images.githubusercontent.com/9715316/158622684-cfc244d7-e62f-44d1-a218-970406af2c39.png)

**Comment by Skillz4Killz** [comment]
Should be fixed now in main. Will be released in next rc version. Thank you for the report
