### ISSUE TITLE
Gateway does not respect firstShardId and lastShardId Option

### ISSUE THREAD

**Issue by meister03** [discordeno/discordeno#2146]
**Describe the bug** A clear and concise description of what the bug is.

Create a simple Bot. Spawn 2 different Bot processes, which uses the shardList: [0,1] and [2,3].

**To Reproduce** Steps to reproduce the behavior:
The bot.gateway.spawnShards does not respect the first ShardId, since its not even a parameter.

Disabled optimal Sharding does not work.

Even if adding the 2nd parameter above, just fixes it for cluster 1, cluster 2 seems to spawn the same shardList.

**Expected behavior** A clear and concise description of what you expected to happen.
Bot spawns the correct shardList

**Screenshots** If applicable, add screenshots to help explain your problem.

**Version details (please complete the following information):**

- Discordeno version: [e.g. 10.5.0]
- Deno version: [e.g. 1.8.0]

**Additional context** Add any other context about the problem here.

**Comment by lts20050703** [comment]
Did this got fixed?
<img width="642" alt="image" src="https://user-images.githubusercontent.com/87189679/168462502-30b81216-5b88-4dfa-8ed3-dc111b410679.png">

**Comment by itohatweb** [comment]
This is the cause of the bug, but a fix is already coming.
