### ISSUE TITLE
Cannot convert string (uuid) to bigint, presence thing.

### ISSUE THREAD

**Issue by ihack2712** [discordeno/discordeno#2170]
<img width="1020" alt="image" src="https://user-images.githubusercontent.com/35933830/164878244-16a8c010-6bf0-4a64-adc6-ec7be8d0ca5e.png">

A member of a server the bot is a member of updated their presence. The bot crashed.

**Comment by Skillz4Killz** [comment]
This was fixed in #2171 will be released soon once I'm back home
