### ISSUE TITLE
[api-docs] Document changes to the upcoming create-thread API for forums (#4850)

### ISSUE THREAD

**Issue by itohatweb** [discordeno/discordeno#2177]
A new commit was made into the api-docs repo: https://github.com/discord/discord-api-docs/commit/17d8be297a5b89413940d9df1a34923907becd2f
No details given.

This is a bot created issue.

**Comment by lts20050703** [comment]
@meister03 Does your merged PR close this issue?

**Comment by meister03** [comment]
Yeah
