### ISSUE TITLE
[api-docs] fix read more link for sku deprecation (#4851)

### ISSUE THREAD

**Issue by itohatweb** [discordeno/discordeno#2178]
A new commit was made into the api-docs repo: https://github.com/discord/discord-api-docs/commit/a4daa52a299019782bff305f1b7d1f756d09ace1
No details given.

This is a bot created issue.

**Comment by lts20050703** [comment]
> fix read more link for sku deprecation
Discord just update a bunch of url that links to sku deprecation
can we close this?
