### ISSUE TITLE
[api-docs] Update Reference.md (#4810)

### ISSUE THREAD

**Issue by itohatweb** [discordeno/discordeno#2179]
A new commit was made into the api-docs repo: https://github.com/discord/discord-api-docs/commit/af8066a8d22d9fad64c92dd0f6c232d82b442779

Changed so that the same filename is used throughout the example.

This is a bot created issue.

**Comment by lts20050703** [comment]
<img width="593" alt="image" src="https://user-images.githubusercontent.com/87189679/167992786-7ad70054-28c3-459e-b869-5f382443c7a2.png">

<img width="812" alt="image" src="https://user-images.githubusercontent.com/87189679/167992802-b5a6b5c2-e04d-4731-8a8f-b9344e8d37bc.png">

> Changed so that the same filename is used throughout the example.

# Can we close this?
