### ISSUE TITLE
[api-docs] Fix Lobby endpoints formatting (#4814)

### ISSUE THREAD

**Issue by itohatweb** [discordeno/discordeno#2181]
A new commit was made into the api-docs repo: https://github.com/discord/discord-api-docs/commit/bf5644506b0bd4c91481860ebc3576e949ed165c

* lobbies fix

* why is that here

This is a bot created issue.

**Comment by lts20050703** [comment]
> Fix Lobby endpoints formatting
Discord fix docs **formatting**. Can we close this?
