### ISSUE TITLE
[api-docs] Remove dm_permission param from Edit Guild Application Command endpoint (#4861)

### ISSUE THREAD

**Issue by itohatweb** [discordeno/discordeno#2185]
A new commit was made into the api-docs repo: https://github.com/discord/discord-api-docs/commit/ceeb0faf8c25aeb26f69c6edbcac95417d9e99b2

* Remove duplicate phrase

* Remove dm_permission parameter from editing guild commands

* Fix table formatting

Thanks @advaith1

Co-authored-by: advaith <advaithj1@gmail.com>

Co-authored-by: advaith <advaithj1@gmail.com>

This is a bot created issue.

**Comment by lts20050703** [comment]
Can we close this? Discord just fix typo and remove `dm_permission` from edit guild application command

Right now we have `createApplicationCommand` and `upsertApplicationCommand` with an optional `guildId` which determine whether it's a guild or global slash command. I think the core lib shouldnt validate that if it's a guild command but there's `dm_permission` (only global slash command can have `dm_permission`, guild slash command cannot have `dm_permission`) then throw new Error , maybe it should be in validation plugin
