### ISSUE TITLE
[api-docs] New oauth scopes (#4917)

### ISSUE THREAD

**Issue by itohatweb** [discordeno/discordeno#2192]
A new commit was made into the api-docs repo: https://github.com/discord/discord-api-docs/commit/3f00c15c4e6e60c2befc7e2e8c6405cef48c8689

* add new OAuth2 scopes

* alphabetical order

* scopes requires Discord approval

This is a bot created issue.

**Comment by lts20050703** [comment]
Can we close this? Discord just add new OAuth scopes
