### ISSUE TITLE
[api-docs] add warning box to user agent docs (#4912)

### ISSUE THREAD

**Issue by itohatweb** [discordeno/discordeno#2201]
A new commit was made into the api-docs repo: https://github.com/discord/discord-api-docs/commit/bc89ebe0718bf528f630787f4fcbc4e9c4e7cde8

* add warning box to user agent docs

* fix spacing

* update CloudFlare to Cloudflare

Co-authored-by: Epic <tagepicuwu@gmail.com>

* update wording

* update wording

* update wording yet again

Co-authored-by: Epic <tagepicuwu@gmail.com>

This is a bot created issue.

**Comment by lts20050703** [comment]
Can we close this? Discord just add a warning box to user agent docs
<img width="375" alt="image" src="https://user-images.githubusercontent.com/87189679/168272778-ffc9b943-b05b-4197-8ccd-6112af4010d5.png">
