### ISSUE TITLE
[api-docs] Commands v2 (#4896)

### ISSUE THREAD

**Issue by itohatweb** [discordeno/discordeno#2204]
A new commit was made into the api-docs repo: https://github.com/discord/discord-api-docs/commit/844c6e4f9023ff573fb54a138cfdca98ea320b13

* Commands v2

* fix overlooked grammatical error

Co-authored-by: Suspense <suspensetm@gmail.com>

* add android note

Co-authored-by: Suspense <suspensetm@gmail.com>

This is a bot created issue.

**Comment by lts20050703** [comment]
Can we close this? Discord finally removing the 1 hour thing for global slash commands
![image](https://user-images.githubusercontent.com/87189679/168273212-1b3376ad-1738-4c98-9852-2f435d7af3e6.png)
![image](https://user-images.githubusercontent.com/87189679/168273215-70056273-170f-4cc8-8e13-071650ef6bf3.png)
![image](https://user-images.githubusercontent.com/87189679/168273220-581a88e5-934e-4a96-8dc4-736a446751e8.png)
![image](https://user-images.githubusercontent.com/87189679/168273227-879df0f6-cf06-4e9f-a05a-54c3f4305f54.png)
