### ISSUE TITLE
fetchMembers

### ISSUE THREAD

**Issue by TriForMine** [discordeno/discordeno#223]
fetchMembers throws an error telling that it requires the GUILD_MEMBERS_INTENT even if we only request 1 user, that actually doesn't require that intent.

**Comment by ayntee** [comment]
> `GUILD_MEMBERS` intent is required to request the entire member list—`(query=‘’, limit=0<=n)`

Source: <https://discord.com/developers/docs/topics/gateway#request-guild-members>

**Comment by ayntee** [comment]
@TriForMine fixed in the `next` branch.
