### ISSUE TITLE
[BREAKING] Property Renames

### ISSUE THREAD

**Issue by Skillz4Killz** [discordeno/discordeno#2230]
This issue will track all the properties or method names that can or is desired to be changed before finalizing the v13 api. Please leave comments below for anything youd like to discuss. This will be one of it not the final PR when v13 is finished.

- [x] message.isBot => message.isFromBot
- [x] gateway.maxShards => gateway.totalShards
- [x] constants.endpoints => constants.routes #2248

**Comment by meister03** [comment]
[[api-docs] Update message type names (#5093) #2322](https://github.com/discordeno/discordeno/issues/2322)
- Done by #2370
