### ISSUE TITLE
Bots cannot use editApplicationCommandPermissions endpoint

### ISSUE THREAD

**Issue by Cristian-A** [discordeno/discordeno#2235]
**Issue**
`editApplicationCommandPermissions` requires a Bearer token so rn it's useless.
https://discord.com/developers/docs/interactions/application-commands#edit-application-command-permissions

**To Reproduce**

```js
await editApplicationCommandPermissions(bot, id, cid, [{
    type: ApplicationCommandPermissionTypes.Role,
    id: Roles.everyone.toString(), permission: false
}, {
    type: ApplicationCommandPermissionTypes.Role,
    id: Roles.moderator.toString(), permission: true
}]);
```

**Expected behavior**
The function should update the permissions of a command to the specified roles.

**Results in**
`{"message":"Bots cannot use this endpoint","code":20001}`

**Notes:**
Should this function be removed? I've been told by user @Skillz4Killz (`Skillz4Killz#8840`) the following:
> I don't think thats possible, it's only possible by user land UNLESS you go through oauth on a website and have them give u a bearer token to use and that makes changes with the USERS token not the bots token
right now bots cant do that

**Comment by itohatweb** [comment]
I know this bug / issue we have rn.
I'll look in how to implement a good fix for that later.

**Comment by itohatweb** [comment]
Could you test whether the PR #2238 fixes your issue?
