### ISSUE TITLE
image in slash command reply embed does not show up

### ISSUE THREAD

**Issue by Cristian-A** [discordeno/discordeno#2236]
**Issue:** When I send an embed through `sendMessage(...)` which contains an image attachment, everything work as expected. By passing the same exact object to `sendInteractionResponse(...)` the image does not show up.

**To Reproduce**

```ts
// object:
{
  file: {
    blob: imageBlob,
    name: 'board.png',
  },
  embeds: [{
    type: 'image', title: 'Chess diagram from FEN position',
    color: game.turn == 'w' ? 0xFFFFFF : 0x000000,
    image: { url: 'attachment://board.png', height: 800, width: 800 },
    footer: { text: status },
  }]
}
```

**Expected behavior:** It should display the image also with `sendInteractionResponse(...)`.

**Screenshots**
#### When sending though `sendMessage(...)`:
<img width="351" alt="Screenshot 2022-05-24 at 5 47 18 PM" src="https://user-images.githubusercontent.com/30161685/170077887-080627df-f70d-4dd1-8db3-aab6292d06a0.png">

#### When sending with `sendInteractionResponse(...)`:
<img width="268" alt="Screenshot 2022-05-24 at 5 48 00 PM" src="https://user-images.githubusercontent.com/30161685/170078043-1190dd57-3b3e-4794-886b-c0ede394cd11.png">

**Comment by itohatweb** [comment]
Can you provide an example code which we can use to reproduce this issue?
