### ISSUE TITLE
[api-docs] add Go API Types (dasgo) to community resources (#4980)

### ISSUE THREAD

**Issue by itohatweb** [discordeno/discordeno#2270]
A new commit was made into the api-docs repo: https://github.com/discord/discord-api-docs/commit/e52157d5e2f4ad59aefed4b65bfe15e64fbd2a7e

* add dasgo to API Types

* fix alphabetical order

add table

This is a bot created issue.

**Comment by lts20050703** [comment]
![Uploading image.png…]()
