### ISSUE TITLE
[api-docs] Separate event specific fields from the Message object (#4915)

### ISSUE THREAD

**Issue by itohatweb** [discordeno/discordeno#2271]
A new commit was made into the api-docs repo: https://github.com/discord/discord-api-docs/commit/43130e5cd041aaa3135237edb1b8127ce8144bd8

* Separate event specific fields from the Message object

* Add note about moving of message fields

Co-authored-by: Shay DeWael <swdewael@gmail.com>

This is a bot created issue.

**Comment by lts20050703** [comment]
@Skillz4Killz You closed #2213 and #2224
Do you want to close this as well?
