### ISSUE TITLE
[api-docs] Remove audit log reference under Modify Guild Channel Positions (#5036)

### ISSUE THREAD

**Issue by itohatweb** [discordeno/discordeno#2275]
A new commit was made into the api-docs repo: https://github.com/discord/discord-api-docs/commit/1f2d399cdef98b4f4603e002e1f8ab5cdc215975
No details given.

This is a bot created issue.

**Comment by lts20050703** [comment]
we forgot to add support for reason but it's removed so we dont need to do anything lol
