### ISSUE TITLE
Possibly bug in rc45

### ISSUE THREAD

**Issue by int0x80-sys** [discordeno/discordeno#2279]
Hi :wave:

So, recently i try the rc45 and i found that the `message` that i receive on `messageCreate` cames with the content empty. I don't know if is something that u are already know or is an actual bug. Simple script to reproduce this:

_mod.ts_
```ts
import { createBot, startBot, Intents } from "./deps.ts";

async function main() {
  const token = Deno.env.get('DS_TOKEN');
  if(!token)
    return;

  const botId = BigInt(atob(token?.split('.')[0]));

  const baseBot = createBot({
    token,
    botId,
    intents: Intents.Guilds | Intents.GuildMessages,
    events: {
      ready() {
        console.log("Successfully connected to gateway");
      },
      messageCreate(_, msg) {
        console.log(msg);
      }
    }
  });

  await startBot(baseBot);
}

await main();
```
_dep.ts_
```ts
export * from "https://deno.land/x/discordeno@13.0.0-rc44/mod.ts";
import "https://deno.land/std@0.143.0/dotenv/load.ts";
```

**Expected behavior**

The content of the message were logged in the console.

**Version details:**

- Discordeno version: v13.0.0-rc45
- Deno version: 1.22.2

Greetings :wave:

**Comment by meister03** [comment]
@latest uses v10 api & gateway. Therefore you have to connect with the message content intent and have it toggled on the dev portal
```js
intents: Intents.Guilds | Intents.GuildMessages | Intents.MessageContent,
```

**Comment by int0x80-sys** [comment]
Hello.

Cool. That solves my problem. Thanks for the clarification. Sorry for the inconvenience

Cheers :wave:
