### ISSUE TITLE
discordeno/@next like alternative

### ISSUE THREAD

**Issue by Skillz4Killz** [discordeno/discordeno#2297]
Make a github action that on each commit it pushes to the deno.land with the commit hash as the tag name so then having no version specified would serve as the @next

**Comment by itohatweb** [comment]
I think something like [denopkg.com](https://denopkg.com) would fit the use case much better. Also since we are now in a stable release road now and do not publish any pre-releases anymore I don't think that we need this.

**Comment by Skillz4Killz** [comment]
Denopkg for the win
