### ISSUE TITLE
[api-docs] Updated identify connection fields to match deprecation status. (#5067)

### ISSUE THREAD

**Issue by itohatweb** [discordeno/discordeno#2306]
A new commit was made into the api-docs repo: https://github.com/discord/discord-api-docs/commit/6755c355caaf2e1c321dc7de17e1e257d9aa2db5

* Updated identify connection fields to match deprecation status.

It is expected that these field names will be supported for a while, but it is recommended to all consumers to update to unprefixed fields.

* Update docs/topics/Gateway.md

* add identify changelog

* ayyy explicit api versions

* Update docs/topics/Gateway.md

Co-authored-by: Zoddo <github@zoddo.fr>

Co-authored-by: Shay <shay.dewael@discordapp.com>
Co-authored-by: Shay DeWael <swdewael@gmail.com>
Co-authored-by: Zoddo <github@zoddo.fr>

This is a bot created issue.

**Comment by Skillz4Killz** [comment]
Please dont open issues without a reason

**Comment by itohatweb** [comment]
Please don't use direct pushes, else I don't know what changes are done to the lib.
Since I just use my memory and don't look the code up.
