### ISSUE TITLE
addRole should check if Bot is owner of server.

### ISSUE THREAD

**Issue by WallyThePenguin** [discordeno/discordeno#236]
**Describe the bug**
addRole checks if the role of the bot is higher than the one from the role it's giving.
What if the bot is the owner of the server.
**To Reproduce**

**Expected behavior**
when the bot is the owner of the server. addRole should also give the role to the user no matter the role the bots have.
**Screenshots**

**Additional context**
Add any other context about the problem here. Please also list the version/branch/commit etc that you are using.
using V9.4.0

**Comment by ayntee** [comment]
On it!
