### ISSUE TITLE
sendRequest is not a method of RestManager

### ISSUE THREAD

**Issue by ySnoopyDogy** [discordeno/discordeno#2380]
**Describe the bug**
the `CreateRestManagerOptions` and the returnType of `createRestmanager` is not including `sendRequest` as a method

**To Reproduce** Write a small mod.ts example to replicate the behavior.

```ts
import { createRestmanager } from "https://deno.land/x/discordeno/mod.ts";

const rest = createRestmanager({
   sendRequest: () => null, // Error: sendRequest is not assignable to parameter of type `CreateRestManagerOptions`
});

rest.sendRequest() // Error: Property 'sendRequest' does not exist on type...
```

**Expected behavior** 
Both option and method should exist in types

**Version details (please complete the following information):**

- Discordeno version: 13.0.0-rc45
- ~Deno~ Node version: 18.6.0

**Additional context** Add any other context about the problem here.
This problem is in the `discordeno/types/rest/restManager.d.ts` file from node_modules, wasn't sure about how to edit it the repo, so there's the issue

**Comment by Skillz4Killz** [comment]
Seems to have been fixed.

![image](https://user-images.githubusercontent.com/23035000/186533204-bcf8fe52-fcea-4510-bccd-21f80d82ef9a.png)
![image](https://user-images.githubusercontent.com/23035000/186533269-37176f9a-d57f-4c46-abb5-5ce0cb6b45df.png)
