### ISSUE TITLE
stopBot does nothing

### ISSUE THREAD

**Issue by BlackAsLight** [discordeno/discordeno#2381]
Do you plan to ever make the function stopBot actually stop the bot?

**Comment by Skillz4Killz** [comment]
@BlackAsLight Hello, i am just getting back in town. Can you please add a bit more details, are you sure the shards are not closing? Can you provide more info to help me debug. On my side it looks like it does work.

**Comment by BlackAsLight** [comment]
I don't know how I'm meant to tell if the shards are closed or not, but when I do it, it says stopped then I get the ready event fired again.
