### ISSUE TITLE
Bun Compatibility

### ISSUE THREAD

**Issue by Skillz4Killz** [discordeno/discordeno#2386]
**Is your feature request related to a problem? Please describe.** A clear and concise description of what the problem
is. Ex. I'm always frustrated when [...]

Work with bun

**Describe the solution you'd like** A clear and concise description of what you want to happen.

Work with bun

**Describe alternatives you've considered** A clear and concise description of any alternative solutions or features
you've considered.

Work with bun

**Additional context** Add any other context or screenshots about the feature request here.

Work with bun

**Comment by lts20050703** [comment]
@Skillz4Killz If https://npmjs.org/package/discordeno doesn't work with bun then isn't that bun's fault?

**Comment by meister03** [comment]
Bun still has buggy websocket support, compression is still a issue and some complicated promise chaining can also fail with a `Segmentation fault` error

**Comment by lts20050703** [comment]
> waiting for [oven-sh/bun#1280](https://github.com/oven-sh/bun/issues/1280) resolve

This has been merged, is there any update on this?

**Comment by H01001000** [comment]
@lts20050703 
waiting for https://github.com/oven-sh/bun/issues/3214
