### ISSUE TITLE
The `getInvites()` helper function only parses the metadata of an invite object, rather than the whole object.

### ISSUE THREAD

**Issue by vxern** [discordeno/discordeno#2389]
As per https://discord.com/developers/docs/resources/guild#get-guild-invites:
> Returns a list of [invite](https://discord.com/developers/docs/resources/invite#invite-object) objects (with [invite metadata](https://discord.com/developers/docs/resources/invite#invite-metadata-object)) for the guild. Requires the MANAGE_GUILD permission.

**Comment by Skillz4Killz** [comment]
Thank you for reporting, fix will be released in next update.
