### ISSUE TITLE
Split the `getWebhooks()` helper into `getWebhooksChannel()` and `getWebhooksGuild()`.

### ISSUE THREAD

**Issue by vxern** [discordeno/discordeno#2434]

**Comment by vxern** [comment]
Update: `getChannelWebhooks()` is found in `/helpers/channels`. This file should be moved to `/helpers/guilds/webhooks` and renamed to `getWebhooksChannel`, while the `getWebhooks` file in `/helpers/guilds/webhooks` should be renamed to `getWebhooksGuild`.

**Comment by lts20050703** [comment]
https://discord.com/developers/docs/resources/webhook#get-channel-webhooks
