### ISSUE TITLE
Deno 1.6 will not run DD without --no-chec

### ISSUE THREAD

**Issue by Skillz4Killz** [discordeno/discordeno#244]
**Describe the bug**
![image](https://user-images.githubusercontent.com/23035000/101689038-e0dc9a00-3a3a-11eb-8d28-0eef3c9210d7.png)

**To Reproduce**
1. Use latest Deno

**Expected behavior**
No errors when not using --no-check

**Screenshots**

**Additional context**
Add any other context about the problem here. Please also list the version/branch/commit etc that you are using.

**Comment by ayntee** [comment]
This is fixed in the next branch.
