### ISSUE TITLE
types: WithReason

### ISSUE THREAD

**Issue by lts20050703** [discordeno/discordeno#2444]
This issue should be expanded to encompass all helper functions as many of them are missing support for this header. Instead of putting a `reason` property in the `options` object parameter found in many of these helper functions, I instead propose to create a type `WithReason<T>`. This type would extend a generic type `T` with a `reason?: string;` field, thus allowing the type of `options` to simply be wrapped in this `WithReason` type.

_Originally posted by @vxern in https://github.com/discordeno/discordeno/issues/2401#issuecomment-1238287856_

**Comment by lts20050703** [comment]
@Skillz4Killz @itohatweb what are your thoughts?

**Comment by Skillz4Killz** [comment]
I love the idea @lts20050703
