### ISSUE TITLE
Support for Slash Commands and Interactions

### ISSUE THREAD

**Issue by itohatweb** [discordeno/discordeno#247]
Discord will be adding slash commands soon. Documentation PR is [here](https://github.com/discord/discord-api-docs/pull/2295) already.

Discordeno should implement that when its out.

To-Do:
- [x] Events
- [x] Controllers
- [x] Handlers
- [x] Structures
- [x] Types

**Comment by ayntee** [comment]
#248 is merged into next; slash commands are usable using `next` branch.
