### ISSUE TITLE
editOriginalInteractionResponse don't parse files

### ISSUE THREAD

**Issue by ySnoopyDogy** [discordeno/discordeno#2482]
**Describe the bug** 

The `helpers.editOriginalInteractionResponse` don't include the files like `helpers.sendInteractionResponse` do

**To Reproduce** Write a small mod.ts example to replicate the behavior.

```ts

bot.helpers.editOriginalInteractionResopnse(interaction.token, {
     file: {
            name: 'OwO.png',
           blob: BlobHere,
}
})
```

**Expected behavior** 
The request should include the correct payload with files

**Screenshots** 
Request data after the reverse transform
![image](https://user-images.githubusercontent.com/59155752/191093685-1797d824-1d50-423b-bd6b-bd0ec4c0ba74.png)
**Version details (please complete the following information):**

- Discordeno version: 16.0.0
- Deno version: **NODE** 18.8.0

**Additional context**

I didn't test it, but looking at the `editFollowUpMessage` code, this same problems should occur there

\>.<

**Comment by itohatweb** [comment]
Hey, thanks for the bug report. I found the issue and will open a fixing PR asap.
