### ISSUE TITLE
Rest no longer sends any requests if "rest.processGlobalQueue" errors

### ISSUE THREAD

**Issue by AwesomeStickz** [discordeno/discordeno#2506]
**Describe the bug:** When you run `rest.runMethod` and give a body such that `rest.processGlobalQueue` throws error (my example here has `TypeError`), rest process will no longer send any requests because `rest.globalQueueProcessing` is set to `true` and will never be set back to `false`, which prevents no other requests to be sent.

**To Reproduce:** I only tested with separate rest process but I'm guessing the same behavior should be there for the other case too. Also, I've only tested this in node.

```ts
import { Blob } from 'buffer';

const buffer: Buffer = // set it to a buffer object

client.helpers.sendMessage("channel id", { file: { name: "something.png", blob: new Blob([buffer]) } });
```

As of v16 (not sure about v17 but that shouldn't matter here (because this blob problem might've been fixed but not this exact issue)), this code should internally throw this error:

![image](https://user-images.githubusercontent.com/38146668/195152651-d1954847-b6c2-47b2-94fe-6cb8798c4a45.png)

A `TypeError`. Now it errors because of `createRequestBody.ts` file, where it would've already had `rest.globalQueueProcessing` as `true`, now to process any other queues (where requests are queued), it must be set to `false` back (afaik) and since it errors and stops halfway, it's never set to `false`, that's where the problem is.

This may be overlooked so I'm mentioning explicitly, the point is to not fix sending blobs (that also has to be if not yet, just not in the scope of this issue) but prevent rest freezing if any error happens internally.

**Version details (please complete the following information):**

- Discordeno version: 16.0.1 (using node)

**Comment by Skillz4Killz** [comment]
Fixed
