### ISSUE TITLE
[api-docs] The ML spam and mention spam AutoMod filters are out (#5397)

### ISSUE THREAD

**Issue by itohatweb** [discordeno/discordeno#2508]
A new commit was made into the api-docs repo: https://github.com/discord/discord-api-docs/commit/cc2fddcb3042b2c7e3908d4a9da27b702539af30

Remove outdated comments now that ML spam filter and mention spam filter
are being released to all servers

This is a bot created issue.

**Comment by Skillz4Killz** [comment]
No effect on code.
