### ISSUE TITLE
[api-docs] Add default_sort_order (#5475)

### ISSUE THREAD

**Issue by itohatweb** [discordeno/discordeno#2510]
A new commit was made into the api-docs repo: https://github.com/discord/discord-api-docs/commit/5e0c9a9c6b79388a4fdadbc798b8563e5861a884

* Add default_sort_order

* Fix links

* Fix description

* Apply suggestions from code review

Co-authored-by: Shay DeWael <swdewael@gmail.com>

* Change mode to type

Co-authored-by: Shay DeWael <swdewael@gmail.com>

This is a bot created issue.

**Comment by Skillz4Killz** [comment]
Reverted in #2514
