### ISSUE TITLE
[api-docs] Clarify `suppress` description in Voice State (#5216)

### ISSUE THREAD

**Issue by itohatweb** [discordeno/discordeno#2511]
A new commit was made into the api-docs repo: https://github.com/discord/discord-api-docs/commit/49ef021fc92f1a08e70ceb2aa06173779fd41fe7

* Clarify `suppress` description in Voice State

It was confusing to `mute` and `self_mute`

* Change wording

* whether this user's permission to speak is denied

This is a bot created issue.

**Comment by Skillz4Killz** [comment]
No change to code
