### ISSUE TITLE
[api-docs] threads: message_count is affected by message creation time (#5437)

### ISSUE THREAD

**Issue by itohatweb** [discordeno/discordeno#2512]
A new commit was made into the api-docs repo: https://github.com/discord/discord-api-docs/commit/dd0b86931461ce87e522299e6c5d9f704c378d2e

* message creation time, not thread creation time affects message_count increment

* Update docs/resources/Channel.md

Co-authored-by: Adrian Paschkowski <git@wasdennnoch.me>

* chore: move note to footnote

* update message

* chore: correct footnote asterisk placement

Co-authored-by: Adrian Paschkowski <git@wasdennnoch.me>

This is a bot created issue.

**Comment by Skillz4Killz** [comment]
No change to code.
