### ISSUE TITLE
[api-docs] Add flags to Guild Channel parameters in Modify Channel (#5469)

### ISSUE THREAD

**Issue by itohatweb** [discordeno/discordeno#2517]
A new commit was made into the api-docs repo: https://github.com/discord/discord-api-docs/commit/5f1e575990fb944189257069ef23594e24e46741

* Missing flags field in Modify Channel

* Add REQUIRE_TAG note

Co-authored-by: Shay DeWael <swdewael@gmail.com>

Co-authored-by: Shay DeWael <swdewael@gmail.com>

This is a bot created issue.

**Comment by Skillz4Killz** [comment]
No code changes necessary.
