### ISSUE TITLE
[api-docs] Add note about new tags when modifying a forum channel: only `name` is required (#5458)

### ISSUE THREAD

**Issue by itohatweb** [discordeno/discordeno#2520]
A new commit was made into the api-docs repo: https://github.com/discord/discord-api-docs/commit/c621fcab1ea055d9abce599c5d2a88dd72aaf533

* add note about tags when modifying a forum channel: only name is required

* put this information in the tag object

* fix order error

* modify wording of note

Co-authored-by: Shay DeWael <swdewael@gmail.com>

* move note above the table

Co-authored-by: Shay DeWael <swdewael@gmail.com>

* fix table

Co-authored-by: Shay DeWael <swdewael@gmail.com>

This is a bot created issue.

**Comment by Skillz4Killz** [comment]
No code changes necessary.
