### ISSUE TITLE
[api-docs] Update to string select (#5544)

### ISSUE THREAD

**Issue by itohatweb** [discordeno/discordeno#2522]
A new commit was made into the api-docs repo: https://github.com/discord/discord-api-docs/commit/3a78b41f1e4b18d0fff875f9937d57297b964a78

* update message component docs for new selects

* standard select -> text select

* update change log

* update with a lil info on members field

* naming oopsies

* Update docs/interactions/Message_Components.md

Co-authored-by: splatterxl <splatterxl@outlook.ie>

* add header

* update to string select to match code

Co-authored-by: splatterxl <splatterxl@outlook.ie>

This is a bot created issue.

**Comment by Skillz4Killz** [comment]
No code changes necessary
