### ISSUE TITLE
[api-docs] Fix markdown fail in Thread Member docs (#5505)

### ISSUE THREAD

**Issue by itohatweb** [discordeno/discordeno#2524]
A new commit was made into the api-docs repo: https://github.com/discord/discord-api-docs/commit/3ff0e4e55126ed47c9064457a2a1128209425e7f

* Fix markdown fail in Thread Member docs

* Update docs/resources/Channel.md

Co-authored-by: ckohen <chaikohen@gmail.com>

Co-authored-by: ckohen <chaikohen@gmail.com>

This is a bot created issue.

**Comment by AFink** [comment]
Why is this even an issue?

**Comment by itohatweb** [comment]
Just, uhm, ye bot created .-.
