### ISSUE TITLE
[api-docs] Split forums docs into sections (#5494)

### ISSUE THREAD

**Issue by itohatweb** [discordeno/discordeno#2527]
A new commit was made into the api-docs repo: https://github.com/discord/discord-api-docs/commit/ab2dd7de6b9503c1c50e3c8fead406e1faac29b6

* split up forum docs into subsections

* update based on feedback

* fix link

* Update Threads.md

This is a bot created issue.

**Comment by Skillz4Killz** [comment]
No code changes required
