### ISSUE TITLE
[api-docs] correct interaction creation success response code (#5208)

### ISSUE THREAD

**Issue by itohatweb** [discordeno/discordeno#2528]
A new commit was made into the api-docs repo: https://github.com/discord/discord-api-docs/commit/63535104817d4395334c5018d723dc306cbcdd35

* add return code definition for command creation when command already exists

* Update docs/interactions/Application_Commands.md

* Update docs/interactions/Application_Commands.md

Co-authored-by: Shay DeWael <swdewael@gmail.com>

This is a bot created issue.

**Comment by Skillz4Killz** [comment]
No code changes necessary
