### ISSUE TITLE
[api-docs] Update THREAD_LIST_SYNC and THREAD_CREATE docs (#5495)

### ISSUE THREAD

**Issue by itohatweb** [discordeno/discordeno#2531]
A new commit was made into the api-docs repo: https://github.com/discord/discord-api-docs/commit/0d925eb4c4af78af367676c148f7db7e95534e58

* Update thread syncing and access docs

* cleanup

* new wording

* Update docs/topics/Threads.md

Co-authored-by: Lala Sabathil <aiko@aitsys.dev>

* Update docs/topics/Threads.md

Co-authored-by: Lala Sabathil <aiko@aitsys.dev>

* update thread syncing docs from feedback

Co-authored-by: Lala Sabathil <aiko@aitsys.dev>

This is a bot created issue.

**Comment by Skillz4Killz** [comment]
No code changes necessary
