### ISSUE TITLE
Cache does not update channel.

### ISSUE THREAD

**Issue by deepsarda** [discordeno/discordeno#2533]
### The cache plugin does not update cache when a channel is updated.

Add CHANNEL_UPDATE to [plugins/cache/src/setupCacheEdits.ts](https://github.com/discordeno/discordeno/blob/main/plugins/cache/src/setupCacheEdits.ts)

_Ability_ to just keep _certain fields_ of kinds like Channel, Guild, etc. in the cache would be a _welcome_ feature that would help _conserve resources._

The object will then need to be _forged_ into the appropriate classes, but you often just need the "id," "name," and other properties for _helper methods_, so this is not necessary.

[Feature in action](https://github.com/meister03/discordeno.js)

I'll shortly be creating my PR with these improvements.
You may contact me here with any comments or suggestions.

Example value for cache plugin.
Based on @meister03 discordeno.js [library](https://github.com/meister03/discordeno.js). 
```ts
{
    guilds: {
        properties: ['id', 'members', 'name', 'roles', 'channels', 'emojis'],
    },
    roles: {
        properties: ['id', 'name', 'permissions'],
    },
    channels: {
        properties: ['id', 'name', 'type', 'messages'],
    },
    users: {
        properties: ['id', 'username', 'discriminator'],
        maxSize: 100,
    },
    members: {
        properties: ['id', 'roles', 'nickname'],
        forceSetFilter: (key, value) => {
                if (key === `${client.id}`) return true; // Sub Collection on Guild Level, pass when client user is the member
                if (key === `${client.id}${value?.guildId}`) return true; // Main Collection, pass when client user is the member of the guild
                return false;
        }
    },
    emojis: {
        properties: ['id', 'name'],
    },
    threads: {
        properties: ['id', 'channelId', 'type'],
    },
    messages: {
        properties: ['id', 'channelId', 'type'],
        // transformerClass: Discord.Message
    },
    stageInstances: {
        properties: ['id', 'guildId', 'type'],
        // transformerClass: Discord.StageInstance
    },
}
```

**Comment by meister03** [comment]
How would you implant partial typings?

**Comment by deepsarda** [comment]
There is a working prototype at https://github.com/discordeno/cache-proxy
