### ISSUE TITLE
[api-docs] add epehmeral delete support (#5570)

### ISSUE THREAD

**Issue by itohatweb** [discordeno/discordeno#2540]
A new commit was made into the api-docs repo: https://github.com/discord/discord-api-docs/commit/8ebc79d47d554d0ba557e2a9103129ee83372fbc
No details given.

This is a bot created issue.

**Comment by lts20050703** [comment]
No need to change anything.

**Comment by lts20050703** [comment]
Actually need to update jsdoc comments
