### ISSUE TITLE
 Redundant parameter in sendInteractionResponse

### ISSUE THREAD

**Issue by Roosteridk** [discordeno/discordeno#2573]
From Discord API documentation: 
>  Responding to interactions does not require a bot token.

Using the bot instance to respond to an interaction when it can just take the interaction token and id is unnecessary. Therefore, I suggest changing `sendInteractionResponse(bot: Bot, interactionId: BigString, token: string, options: InteractionResponse)` function to `sendInteractionResponse(interactionId: BigString, BigString, token: string, options: InteractionResponse)`

**Comment by itohatweb** [comment]
This is not how this lib works. The bot instance does not need to be connected to the gateway. You can just create it and interact with Discords API.

**Comment by Roosteridk** [comment]
Yea that's the point; we don't need the bot instance at all when responding to the interaction which eliminates the point of having that as a parameter in the first place.

**Comment by itohatweb** [comment]
We need it because we need to handle rate limits.

**Comment by Roosteridk** [comment]
> Interaction endpoints are not bound to the bot's Global Rate Limit.
https://discord.com/developers/docs/topics/rate-limits#global-rate-limit

**Comment by itohatweb** [comment]
Yes, not the global rate limit, but they still have a rate limit. Which when exceed too often can give you an IP ban.

**Comment by Roosteridk** [comment]
I see, thanks for the clarification!
