### ISSUE TITLE
[Rest] Rest doesn't calculate ratelimits properly and takes a lot of time to send requests on large scale

### ISSUE THREAD

**Issue by AwesomeStickz** [discordeno/discordeno#2578]
I'm not too sure about what exactly is the cause of this but I believe it's because of using `x-ratelimit-bucket` to identify a bucket, whereas in Discord API that's not the case at all, it's only intended for grouping similar rate limit routes and not for uniquely identifying a bucket. But that's just my guess tho, someone has to deep check it to verify where's the problem.

I explained in detail in the Discord server here: https://discord.com/channels/785384884197392384/785384884197392387/1039513701599940619

My bot was sending requests too slow that it took lots of mins to send messages simply because of not handling ratelimits correctly, now I've replaced dd rest with eris rest code and it works perfectly fine so the problem is surely there with dd rest, I'm just not 100% sure about the cause, my guess is it's only `x-ratelimit-bucket` but it could be a combination of multiple bugs, someone with more knowledge has to look into this, please fix it, thanks

**Comment by deepsarda** [comment]
@AwesomeStickz Can you share the code with me.
![image](https://user-images.githubusercontent.com/92147339/201515073-e759a004-d648-42dc-9ea3-0955a168f088.png)
Image of me facing this issue. This is the length of rest queue length

**Comment by AwesomeStickz** [comment]
I've shared in the Discord link I sent, it's somewhere there: https://discord.com/channels/785384884197392384/785384884197392387/1039513701599940619

**Comment by Skillz4Killz** [comment]
Fixed
