### ISSUE TITLE
[Rest] Request go out of order after reaching rate limit

### ISSUE THREAD

**Issue by H01001000** [discordeno/discordeno#2579]
After the request push to the global queue and the rate limit happens, the global queue will remove it from the queue and add it back after the time out. If there are other request behind that request, there is a chance that those requests are not taken away from the queue and run before the taken-away request, causing the request out of order.

Idea:
I think we should be more careful with the request and amount of requests we push to the global queue, like only pushing x-ratelimit-limit amount of requests to the global queue, and implement token bucket

**Comment by Skillz4Killz** [comment]
Fixed
