### ISSUE TITLE
Directories & files organization

### ISSUE THREAD

**Issue by Skillz4Killz** [discordeno/discordeno#258]
Cleanup and make better folder system
  - Move rest & ws to its own folders
  - Fix any other organiztion thats obvious that was originally done as a rush to just get it done

This is just an example 
```
src
  api
    mod.ts
    deps.ts
    // structures and handlers and such
  rest
    mod.ts
    deps.ts
  ws
    mod.ts
    deps.ts
  interactions
    mod.ts
    deps.ts
```

Cleanup and make better file names
  - example we don't have a concept like `client` so src/modules/client.ts` makes almost no sense. Maybe init.ts or something not sure but we need to think of better names

**Comment by ayntee** [comment]
As previously discussed, `client.ts` is to be renamed to `bot.ts`.

**Comment by ayntee** [comment]
We can publish multiple modules from one repository; so we can publish ws and rest as individual modules to deno.land/x

**Comment by ayntee** [comment]
Also, it feels weird to segregate `interactions` from everything else.

**Comment by ayntee** [comment]
Should `structures` really be in `api` directory?

**Comment by ayntee** [comment]
```
- structs/
- api/
    - rest/
    - ws/
    - types/
    - handlers/
    - controllers
- interactions/
```
What do you think about this?

**Comment by Skillz4Killz** [comment]
> Also, it feels weird to segregate `interactions` from everything else.

This is up to you, imo it can be separate atleast the https portion not the Gateway portion. The reason is because u can now have an entire bot working without anything but the interactions so it would be nice to have a simple url u can just only use interactions code and not the rest of stuff

**Comment by Skillz4Killz** [comment]
> Should `structures` really be in `api` directory? "Structures" is not a part of the Discord API, we internally create "structure" for members, guilds, etc.
> 
> ```
> - structs/
> - api/
>     - rest/
>     - ws/
>     - types/
>     - handlers/
>     - controllers
> - interactions/
> ```
> 
> What do you think about this?

Wouldnt the same apply to like handlers/controllers?

**Comment by ayntee** [comment]
> > Should `structures` really be in `api` directory? "Structures" is not a part of the Discord API, we internally create "structure" for members, guilds, etc.
> > ```
> > - structs/
> > - api/
> >     - rest/
> >     - ws/
> >     - types/
> >     - handlers/
> >     - controllers
> > - interactions/
> > ```
> > 
> > 
> > What do you think about this?
> 
> Wouldnt the same apply to like handlers/controllers? Maybe `lib` is better than `api`

`lib`, it is then!
