### ISSUE TITLE
feat req: helpers: getGuildAvatarURL()

### ISSUE THREAD

**Issue by Kira-Kitsune** [discordeno/discordeno#2677]
**Is your feature request related to a problem? Please describe.** A clear and concise description of what the problem
is. Ex. I'm always frustrated when [...]
I'm trying to get the user's guild avatar (if have one) and need the CDN url for it.
 
**Describe the solution you'd like** A clear and concise description of what you want to happen.
Similar to getAvatarUrl(), one for guild avatar or an option in this function for guild avatars.

**Comment by AwesomeStickz** [comment]
> https://github.com/discordeno/discordeno/blob/main/helpers/guilds/getGuildIconUrl.ts

You're talking about guild icon url while the issue is about getting the member's avatar url in that guild, idk the solution but I just felt like clarifying it @Skillz4Killz
