### ISSUE TITLE
icon_hash, image_hash, discovery_splash_hash, banner_hash and splash_hash trying to be parsed as a bigint.

### ISSUE THREAD

**Issue by deepsarda** [discordeno/discordeno#2680]
**Describe the bug** Trying to convert non bigint snowflake to bigint.
**To Reproduce** Fetch auditlog of a guild.
**Expected behavior** No Errors 

![image](https://user-images.githubusercontent.com/92147339/206489801-32ce50ed-3db2-4c94-add1-61ade49dd72d.png)

**Comment by Skillz4Killz** [comment]
Fixed
