### ISSUE TITLE
utils.calculateShardId() not working properly when having separate gateway manager process

### ISSUE THREAD

**Issue by AwesomeStickz** [discordeno/discordeno#2711]
Title is pretty much self explanatory, it's not working properly because it access gateway manager as first param which is used to get total shards, which is `1`, so the return value of this util function is always `0`, which isn't expected.

This is a big problem in some parts of the code like `client.helpers.fetchMembers()` if a bot relies on that.

**Comment by Skillz4Killz** [comment]
Fixed
