### ISSUE TITLE
Many helpers related to shards not working when using proxy gateway

### ISSUE THREAD

**Issue by AwesomeStickz** [discordeno/discordeno#2712]
While finding #2711, I found that the `fetchMembers` helper won't work at all for bots that uses proxy gateway, so I wanted to list all of them that won't work due to this issue, these are all the helpers that won't work when using proxy gateway:

- connectToVoiceChannel
- leaveVoiceChannel
- fetchMembers
- editBotStatus
- editShardStatus

If more info needed about why this happens: 

Proxy gateway is the only process with shards data, the bot process won't have it at all, so anywhere in dd we use `shards.get()`, it'll never be able to find a shard, thus these helpers above will never work as all of them makes use of `gateway.manager.shards.get()`

**Comment by Skillz4Killz** [comment]
These helpers were removed from bot in v19 and moved to gateway package. 

Bot developers, will need a manner of communication between the bot and the gateway asking the gateway to fetch members for example
