### ISSUE TITLE
Bug: v18 Rest not sending request after fetching something

### ISSUE THREAD

**Issue by H01001000** [discordeno/discordeno#2766]
On Discordeno v18 there is a bug where after a get request/fetch, it will stop sending any other rest request (in the same queue). 

Reason: After a rest rewrite, it expects every request to return the rate limit header, and decide whether or not to send another request according to the remaining header. But get request/ fetch won't return the rate limit header, thus the next request is stuck forever

Workaround: Downgrade to v17 or update to v19 (unstable)

**Comment by Skillz4Killz** [comment]
Fixed in 19
