### ISSUE TITLE
fetchMembers doesn't return anything

### ISSUE THREAD

**Issue by TriForMine** [discordeno/discordeno#277]
fetchMembers doesn't return anything and break the code, even only an await will stop the code and never execute the rest of the code.

Example:
```ts
console.log('fetching');
await fetchMembers(guild, { userIDs: [id], limit: 1 }).catch(console.error).then(console.log);
console.log('done');
```
'done' will never get logged and neither anything else is not logged.

**Comment by ayntee** [comment]
Fixed in `v10`.
```
https://deno.land/x/discordeno@10.0.0/mod.ts
```
