### ISSUE TITLE
Bug(utils): call calculatePermissions will result in SyntaxError

### ISSUE THREAD

**Issue by H01001000** [discordeno/discordeno#2775]
Error:
Calling `calculatePermissions(34393292864n)` will cause `SyntaxError: Cannot convert CREATE_INSTANT_INVITE to a BigInt`

Expect:
return `['ADD_REACTIONS', 'CREATE_PUBLIC_THREADS', 'USE_VAD']` without following the order

Test:
`expect(calculatePermissions(34393292864n)).to.have.members(['ADD_REACTIONS', 'CREATE_PUBLIC_THREADS', 'USE_VAD'])`

**Comment by lts20050703** [comment]
I have identified the cause of this
This is the typescript source code
![image](https://user-images.githubusercontent.com/87189679/217763181-de4d67ad-3790-4107-8d87-fc5bd612db90.png)
This is what it compiles to
![image](https://user-images.githubusercontent.com/87189679/217763265-fb91982e-6816-4d0f-b51e-b4b7c6f0fcb3.png)
The typescript compiler is dumb
It compile `if(Number(permission)) return false` to `typeof permission !== "number"`

`if(Number("1"))` return 1, therefore it will then run `return false`, but `typeof permission !== "number"` return true, therefore it bypass the check

**Comment by H01001000** [comment]
@lts20050703 changing the object key to object value solved it
