### ISSUE TITLE
Rest: add helpers

### ISSUE THREAD

**Issue by H01001000** [discordeno/discordeno#2780]
- [x] Rest add: addReaction helper
- [x] Rest: add addReactions helper
- [x] Rest: add addRole helper
- [x] Rest: add addThreadMember helper
- [x] Rest: add banMember helper
- [x] Rest: add connectToVoiceChannel helper
- [x] Rest: add createAutomodRule helper
- [x] Rest: add createChannel helper
- [x] Rest: add createEmoji helper
- [x] Rest: add createForumThread helper
- [x] Rest: add createGlobalApplicationCommand helper
- [x] Rest: add createGuild helper
- [x] Rest: add createGuildApplicationCommand helper
- [x] Rest: add createGuildFromTemplate helper
- [x] Rest: add createGuildSticker helper
- [x] Rest: add createGuildTemplate helper
- [x] Rest: add createInvite helper
- [x] Rest: add createRole helper
- [x] Rest: add createScheduledEvent helper
- [x] Rest: add createStageInstance helper
- [x] Rest: add createWebhook helper
- [x] Rest: add crosspostMessage helper
- [x] Rest: add deleteAutomodRule helper
- [x] Rest: add deleteChannel helper
- [x] Rest: add deleteChannelPermissionOverride helper
- [x] Rest: add deleteEmoji helper
- [x] Rest: add deleteFollowupMessage helper
- [x] Rest: add deleteGlobalApplicationCommand helper
- [x] Rest: add deleteGuild helper
- [x] Rest: add deleteGuildApplicationCommand helper
- [x] Rest: add deleteGuildSticker helper
- [x] Rest: add deleteGuildTemplate helper
- [x] Rest: add deleteIntegration helper
- [x] Rest: add deleteInvite helper
- [x] Rest: add deleteMessage helper
- [x] Rest: add deleteMessages helper
- [x] Rest: add deleteOriginalInteractionResponse helper
- [x] Rest: add deleteOwnReaction helper
- [x] Rest: add deleteReactionsAll helper
- [x] Rest: add deleteReactionsEmoji helper
- [x] Rest: add deleteRole helper
- [x] Rest: add deleteScheduledEvent helper
- [x] Rest: add deleteStageInstance helper
- [x] Rest: add deleteUserReaction helper
- [x] Rest: add deleteWebhook helper
- [x] Rest: add deleteWebhookMessage helper
- [x] Rest: add deleteWebhookWithToken helper
- [x] Rest: add editApplicationCommandPermissions helper
- [x] Rest: add editAutomodRule helper
- [x] Rest: add editBotMember helper
- [x] Rest: add editBotProfile helper
- [x] Rest: add editBotStatus helper
- [x] Rest: add editChannel helper
- [x] Rest: add editChannelPermissionOverrides helper
- [x] Rest: add editChannelPositions helper
- [x] Rest: add editEmoji helper
- [x] Rest: add editFollowupMessage helper
- [x] Rest: add editGlobalApplicationCommand helper
- [x] Rest: add editGuild helper
- [x] Rest: add editGuildApplicationCommand helper
- [x] Rest: add editGuildMfaLevel helper
- [x] Rest: add editGuildSticker helper
- [x] Rest: add editGuildTemplate helper
- [x] Rest: add editMember helper
- [x] Rest: add editMessage helper
- [x] Rest: add editOriginalInteractionResponse helper
- [x] Rest: add editOriginalWebhookMessage helper
- [x] Rest: add editOwnVoiceState helper
- [x] Rest: add editRole helper (editRolePositions)
- [x] Rest: add editScheduledEvent helper
- [x] Rest: add editShardStatus helper
- [x] Rest: add editStageInstance helper
- [x] Rest: add editUserVoiceState helper
- [x] Rest: add editWebhook helper
- [x] Rest: add editWebhookMessage helper
- [x] Rest: add editWebhookWithToken helper
- [x] Rest: add editWelcomeScreen helper
- [x] Rest: add editWidgetSettings helper
- [x] Rest: add executeWebhook helper
- [x] Rest: add fetchMembers helper
- [x] Rest: add followAnnouncementChannel helper (followAnnouncement)
- [x] Rest: add getActiveThreads helper
- [x] Rest: add getApplicationCommandPermission helper
- [x] Rest: add getApplicationCommandPermissions helper
- [x] Rest: add getApplicationInfo helper
- [x] Rest: add getAuditLog helper
- [x] Rest: add getAutomodRule helper
- [x] Rest: add getAutomodRules helper
- [x] Rest: add getAvailableVoiceRegions helper
- [x] Rest: add getAvatarURL helper
- [x] Rest: add getBan helper
- [x] Rest: add getBans helper
- [x] Rest: add getChannel helper
- [x] Rest: add getChannelInvites helper
- [x] Rest: add getChannelWebhooks helper
- [x] Rest: add getChannels helper
- [x] Rest: add getDmChannel helper
- [x] Rest: add getEmoji helper
- [x] Rest: add getEmojiURL helper
- [x] Rest: add getEmojis helper
- [x] Rest: add getFollowupMessage helper
- [x] Rest: add getGatewayBot helper (getSessionInfo)
- [x] Rest: add getGlobalApplicationCommand helper
- [x] Rest: add getGlobalApplicationCommands helper
- [x] Rest: add getGuild helper
- [x] Rest: add getGuildApplicationCommand helper
- [x] Rest: add getGuildApplicationCommands helper
- [x] Rest: add getGuildBannerURL helper
- [x] Rest: add getGuildIconURL helper
- [x] Rest: add getGuildPreview helper
- [x] Rest: add getGuildSplashURL helper
- [x] Rest: add getGuildSticker helper
- [x] Rest: add getGuildStickers helper
- [x] Rest: add getGuildTemplate helper
- [x] Rest: add getGuildTemplates helper
- [x] Rest: add getGuildWebhooks helper
- [x] Rest: add getIntegrations helper
- [x] Rest: add getInvite helper
- [x] Rest: add getInvites helper
- [x] Rest: add getMember helper
- [x] Rest: add getMembers helper
- [x] Rest: add getMessage helper
- [x] Rest: add getMessages helper
- [x] Rest: add getNitroStickerPacks helper
- [x] Rest: add getOriginalInteractionResponse helper
- [x] Rest: add getPinnedMessages helper
- [x] Rest: add getPrivateArchivedThreads helper
- [x] Rest: add getPrivateJoinedArchivedThreads helper
- [x] Rest: add getPruneCount helper
- [x] Rest: add getPublicArchivedThreads helper
- [x] Rest: add getReactions helper
- [x] Rest: add getRoles helper
- [x] Rest: add getScheduledEvent helper
- [x] Rest: add getScheduledEventUsers helper
- [x] Rest: add getScheduledEvents helper
- [x] Rest: add getStageInstance helper
- [x] Rest: add getSticker helper
- [x] Rest: add getThreadMember helper
- [x] Rest: add getThreadMembers helper
- [x] Rest: add getUser helper
- [x] Rest: add getVanityUrl helper
- [x] Rest: add getVoiceRegions helper
- [x] Rest: add getWebhook helper
- [x] Rest: add getWebhookMessage helper
- [x] Rest: add getWebhookWithToken helper
- [x] Rest: add getWelcomeScreen helper
- [x] Rest: add getWidget helper
- [x] Rest: add getWidgetImageURL helper
- [x] Rest: add getWidgetSettings helper
- [x] Rest: add isGetMessagesAfter helper
- [x] Rest: add isGetMessagesAround helper
- [x] Rest: add isGetMessagesBefore helper
- [x] Rest: add isGetMessagesLimit helper
- [x] Rest: add joinThread helper
- [x] Rest: add kickMember helper
- [x] Rest: add leaveGuild helper
- [x] Rest: add leaveThread helper
- [x] Rest: add leaveVoiceChannel helper
- [x] Rest: add modifyRolePositions helper
- [x] Rest: add pinMessage helper
- [x] Rest: add processReactionString helper
- [x] Rest: add pruneMembers helper
- [x] Rest: add publishMessage helper
- [x] Rest: add removeRole helper
- [x] Rest: add removeThreadMember helper
- [x] Rest: add searchMembers helper
- [x] Rest: add sendFollowupMessage helper
- [x] Rest: add sendInteractionResponse helper
- [x] Rest: add sendMessage helper
- [x] Rest: add sendWebhookMessage helper
- [x] Rest: add startThreadWithMessage helper
- [x] Rest: add startThreadWithoutMessage helper
- [x] Rest: add startTyping helper
- [x] Rest: add swapChannels helper
- [x] Rest: add syncGuildTemplate helper
- [x] Rest: add triggerTypingIndicator helper
- [x] Rest: add unbanMember helper
- [x] Rest: add unpinMessage helper
- [x] Rest: add updateBotVoiceState helper
- [x] Rest: add upsertGlobalApplicationCommands helper
- [x] Rest: add upsertGuildApplicationCommands helper

**Comment by Skillz4Killz** [comment]
Done
