### ISSUE TITLE
Unit Tests

### ISSUE THREAD

**Issue by Skillz4Killz** [discordeno/discordeno#281]
We have room for a lot more unit tests to be added

**Comment by ayntee** [comment]
Tests for what?

**Comment by Skillz4Killz** [comment]
Each and every function

**Comment by ayntee** [comment]
> Each and every function

I don't think that is feasible, considering we are live-testing the API.

**Comment by Skillz4Killz** [comment]
Why not? It was always planned for every function to be tested live from the start.

**Comment by Skillz4Killz** [comment]
https://docs.github.com/en/free-pro-team@latest/developers/webhooks-and-events/webhook-events-and-payloads#issue_comment

I would like to somehow use this to trigger the workflow to test this way when one of the contributors of the repo leave a comment on a PR once its finalized we can leave a comment like `deno test` and it would run the tests
