### ISSUE TITLE
Missing arguments, Missing properyties 

### ISSUE THREAD

**Issue by livelove1987** [discordeno/discordeno#3024]
`unbanMember` function doesnt have reason argument **(In rest package, in bot package works fine )**
`guildCreate` event does not contain threads

- Discordeno version: 19.0.0-next.e2d86ea
- Node version: v18.15.0

**Comment by Skillz4Killz** [comment]
Fixed guildCreate bug!

Unban member not a bug:
<img width="574" alt="image" src="https://user-images.githubusercontent.com/23035000/236904273-a271783e-86c1-4afe-8d4e-3ce26ce78b19.png">
