### ISSUE TITLE
[api-docs] Update invite gateway event docs (#6131)

### ISSUE THREAD

**Issue by itohatweb** [discordeno/discordeno#3042]
A new commit was made into the api-docs repo: https://github.com/discord/discord-api-docs/commit/625a0c2c53a4378b5b407e74e44cb672fb9eaf3f

* Update invite gateway event docs

* Update docs/topics/Gateway_Events.md

Co-authored-by: Andrin S. <65789180+Puncher1@users.noreply.github.com>

---------

Co-authored-by: Andrin S. <65789180+Puncher1@users.noreply.github.com>

This is a bot created issue.

**Comment by Skillz4Killz** [comment]
No code changes required.
