### ISSUE TITLE
[api-docs] Update Intro page for docs (#6213)

### ISSUE THREAD

**Issue by itohatweb** [discordeno/discordeno#3047]
A new commit was made into the api-docs repo: https://github.com/discord/discord-api-docs/commit/e568170f7cfa3c35c9769b7bd0e5a08054afd58a

* update intro page content

* update intro smul

* add line

* small edit because reuse

* small edits

* Update docs/Intro.mdx

Co-authored-by: Jiralite <33201955+Jiralite@users.noreply.github.com>

---------

Co-authored-by: Jiralite <33201955+Jiralite@users.noreply.github.com>

This is a bot created issue.

**Comment by Skillz4Killz** [comment]
No code changes required.
