### ISSUE TITLE
[api-docs] Update channel create message request size limit (#6092)

### ISSUE THREAD

**Issue by itohatweb** [discordeno/discordeno#3050]
A new commit was made into the api-docs repo: https://github.com/discord/discord-api-docs/commit/dd48c4820664ea4c20f5f8195d136e7f2639d91d

* fix: channel create message request size limit

* fix: update max request size in start thread in forum channel

This is a bot created issue.

**Comment by Skillz4Killz** [comment]
No code changes required.
