### ISSUE TITLE
[api-docs] Username Docs Updates (#6218)

### ISSUE THREAD

**Issue by itohatweb** [discordeno/discordeno#3051]
A new commit was made into the api-docs repo: https://github.com/discord/discord-api-docs/commit/6e9622bec117934aba362bb8c6b0389ef4c3f794

* start username docs

* default avatar

* Update docs/Reference.md

Co-authored-by: Florian Spieß <business@minn.dev>

* Update docs/Change_Log.md

Co-authored-by: Néstor Pérez <25409753+prryplatypus@users.noreply.github.com>

* fix docs

* reorder

* clarify migrated/legacy

* small changelog clarification

* Update docs/Change_Log.md

Co-authored-by: Florian Spieß <business@minn.dev>

* Update docs/Reference.md

Co-authored-by: Florian Spieß <business@minn.dev>

* oops

* great

---------

Co-authored-by: Florian Spieß <business@minn.dev>
Co-authored-by: Néstor Pérez <25409753+prryplatypus@users.noreply.github.com>

This is a bot created issue.

**Comment by AwesomeStickz** [comment]
Done - https://github.com/discordeno/discordeno/pull/3035
