### ISSUE TITLE
[api-docs] Change URL for original snowflake documentation to twitter-archive (#6216)

### ISSUE THREAD

**Issue by itohatweb** [discordeno/discordeno#3055]
A new commit was made into the api-docs repo: https://github.com/discord/discord-api-docs/commit/17601fc9524163e1521d9e8f10649f7b1f2d22ab

While the original URL using the "twitter" organisation does redirect to the intended destination (at "twitter-archive"), the "twitter" org is exists for other purposes currently and this would make the link not rely on GitHub's redirection.

This is a bot created issue.

**Comment by Skillz4Killz** [comment]
No code changes required.
