### ISSUE TITLE
[api-docs] update emoji gateway event information (#6135)

### ISSUE THREAD

**Issue by itohatweb** [discordeno/discordeno#3059]
A new commit was made into the api-docs repo: https://github.com/discord/discord-api-docs/commit/298ee7a7abf02ab6dd0944f9493c4dd5b71be31f

`MESSAGE_REACTION_REMOVE` and `MESSAGE_REACTION_REMOVE_EMOJI` has the field `emoji`.`animated` now.

This is a bot created issue.

**Comment by Skillz4Killz** [comment]
No code changes required.
