### ISSUE TITLE
[api-docs] Minor Wording Fix (#6280)

### ISSUE THREAD

**Issue by itohatweb** [discordeno/discordeno#3082]
A new commit was made into the api-docs repo: https://github.com/discord/discord-api-docs/commit/ff13b3189898bb3c7b6f5b0a88b14ea1d73303a4

* Minor Wording Fix

Bot users are now automatically attached to newly created applications. This part of the docs is outdated.

* Update docs/interactions/Receiving_and_Responding.md

Co-authored-by: shay <swdewael@gmail.com>

* Update docs/interactions/Receiving_and_Responding.md

Co-authored-by: shay <swdewael@gmail.com>

* Update docs/interactions/Receiving_and_Responding.md

---------

Co-authored-by: shay <swdewael@gmail.com>

This is a bot created issue.

**Comment by Skillz4Killz** [comment]
No code changes required.
