### ISSUE TITLE
[api-docs] Add changelog entry for application connection metadata and linked roles (#5851)

### ISSUE THREAD

**Issue by itohatweb** [discordeno/discordeno#3083]
A new commit was made into the api-docs repo: https://github.com/discord/discord-api-docs/commit/78fb89d9d038666e61d6005d014642192ffe0ca5

* Update Change_Log.md

* Update Change_Log.md

* Update Change_Log.md

* Update Change_Log.md

* Update docs/Change_Log.md

Co-authored-by: Suspense <64612795+AlmostSuspense@users.noreply.github.com>

* Update docs/Change_Log.md

* Update docs/Change_Log.md

* Update docs/Change_Log.md

---------

Co-authored-by: Suspense <64612795+AlmostSuspense@users.noreply.github.com>
Co-authored-by: shay <swdewael@gmail.com>

This is a bot created issue.

**Comment by Skillz4Killz** [comment]
No code changes required.
