### ISSUE TITLE
[api-docs] Document with_counts param for GET /users/@me/guilds (#5628)

### ISSUE THREAD

**Issue by itohatweb** [discordeno/discordeno#3085]
A new commit was made into the api-docs repo: https://github.com/discord/discord-api-docs/commit/ee1de009356b9ca1d11c872592854f262e38e463

* Document with_counts param for GET /users/@me/guilds

* Update docs/resources/Guild.md

---------

Co-authored-by: shay <swdewael@gmail.com>

This is a bot created issue.

**Comment by Skillz4Killz** [comment]
No code changes required.
