### ISSUE TITLE
bot doesnt run on bun

### ISSUE THREAD

**Issue by desplmfao** [discordeno/discordeno#3103]
**Describe the bug** 
bot doesnt run on bun

**To Reproduce** (used this code in the screenshot)

```ts
import * as discord from 'discordeno';

const clientOptions: discord.CreateBotOptions = {
    token: process.env['TOKEN'] || '',
    intents:
        discord.Intents.Guilds |
        discord.Intents.GuildMessages |
        discord.Intents.MessageContent,
};

const client = discord.createBot(clientOptions);

await discord.startBot(client);

```

**Expected behavior** 
the bot would run without issues

**Screenshots** 
https://media.discordapp.net/attachments/1141826681175281786/1144070691944153099/image.png

**Version details (please complete the following information):**

- Discordeno version: 18.0.1
- Bun version: 0.8.0 (doesnt work on previous lts either)

**Comment by Fleny113** [comment]
Discordeno v18 does not work with bun. You have to use the v19 package(s)

Here is the equivalent of your code using v19
```ts
import { createBot, Intents } from "@discordeno/bot";

const bot = createBot({
    token: process.env.TOKEN,
    intents: Intents.Guilds | Intents.GuildMessages | Intents.MessageContent,
});

await bot.start();
```

---

Note that in discordeno v19 you have to specify what proprieties you want from discord, so if you need to get the message content you need to add this line: 
```ts
bot.transformers.desiredProperties.message.content = true
```
This also applies to
- Getting the id of a guild/channel/message/user
- Getting the id and token for an interaction

And most other proprieties

**Comment by Fleny113** [comment]
> ```
>         case !message.content.startsWith(config.bot.prefix):
>                       ^
> 
> 
> TypeError: Cannot read properties of undefined (reading 'content')
> ```
 
Your problem is another, the error is about `message` being undefined, not `content` being undefined, since it's saying he can't read the propriety content from undefined

**Comment by Fleny113** [comment]
> ok, ill see what the problem is

from the small context i have of the error, you are using it in a switch case and you can't use variables in the cases of a switch from what I remember
