### ISSUE TITLE
[api-docs] Update teams docs (#6372)

### ISSUE THREAD

**Issue by itohatweb** [discordeno/discordeno#3105]
A new commit was made into the api-docs repo: https://github.com/discord/discord-api-docs/commit/80b0958e70f443dd8b145ec4b51a0eb04013b83a

* Update Teams docs

* small edit

* move into table

* update assets

* update other table

* add changelog

* small clarif

* table formatting

This is a bot created issue.

**Comment by Fleny113** [comment]
Issue related to [discord/discord-api-docs](https://github.com/discord/discord-api-docs) can be useful and keeping them is a better idea until they get addressed
