### ISSUE TITLE
[api-docs] Standard stickers are now free (#6265)

### ISSUE THREAD

**Issue by itohatweb** [discordeno/discordeno#3107]
A new commit was made into the api-docs repo: https://github.com/discord/discord-api-docs/commit/d289f8fbfe011b553089d9ca345e053dd6893a08

* Standard stickers are now free

* Update docs/resources/Sticker.md

Co-authored-by: shay <swdewael@gmail.com>

---------

Co-authored-by: shay <swdewael@gmail.com>

This is a bot created issue.

**Comment by Fleny113** [comment]
Issue related to [discord/discord-api-docs](https://github.com/discord/discord-api-docs) can be useful and keeping them is a better idea until they get addressed

**Comment by MatthewSH** [comment]
Quick doc update for StickerTypes
