### ISSUE TITLE
[api-docs] Document integration_type for audit log entries (#6367)

### ISSUE THREAD

**Issue by itohatweb** [discordeno/discordeno#3108]
A new commit was made into the api-docs repo: https://github.com/discord/discord-api-docs/commit/e27f5215c72d779442c6fbd464c979626afcf854
No details given.

This is a bot created issue.

**Comment by Fleny113** [comment]
Issue related to [discord/discord-api-docs](https://github.com/discord/discord-api-docs) can be useful and keeping them is a better idea until they get addressed
