### ISSUE TITLE
[api-docs] Bump word-wrap from 1.2.3 to 1.2.4 (#6309)

### ISSUE THREAD

**Issue by itohatweb** [discordeno/discordeno#3109]
A new commit was made into the api-docs repo: https://github.com/discord/discord-api-docs/commit/956d9a3a634fbc4b16fa29fafd28afd19fdfd4c6

Bumps [word-wrap](https://github.com/jonschlinkert/word-wrap) from 1.2.3 to 1.2.4.
- [Release notes](https://github.com/jonschlinkert/word-wrap/releases)
- [Commits](https://github.com/jonschlinkert/word-wrap/compare/1.2.3...1.2.4)

---
updated-dependencies:
- dependency-name: word-wrap
  dependency-type: indirect
...

Signed-off-by: dependabot[bot] <support@github.com>
Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>

This is a bot created issue.

**Comment by Skillz4Killz** [comment]
No code changes required.
