### ISSUE TITLE
[api-docs] Clarify return values for Text Input components in an interaction (#6344)

### ISSUE THREAD

**Issue by itohatweb** [discordeno/discordeno#3110]
A new commit was made into the api-docs repo: https://github.com/discord/discord-api-docs/commit/19581c8be17d41920a1b5f6af562f2cbb7bd16a3

* Clarify return values for Text Input components in an interaction

* Fix link to text-input-object-text-input-styles

* Update docs/interactions/Message_Components.md

Co-authored-by: shay <swdewael@gmail.com>

* Clarify returned attributes when using text input

Co-authored-by: shay <swdewael@gmail.com>

---------

Co-authored-by: shay <swdewael@gmail.com>

This is a bot created issue.

**Comment by Fleny113** [comment]
Issue related to [discord/discord-api-docs](https://github.com/discord/discord-api-docs) can be useful and keeping them is a better idea until they get addressed
