### ISSUE TITLE
[api-docs] Add Guild Navigation Message Format (#6105)

### ISSUE THREAD

**Issue by itohatweb** [discordeno/discordeno#3112]
A new commit was made into the api-docs repo: https://github.com/discord/discord-api-docs/commit/e8110aed41aee61e0413d96a40ba3c0b05fcfdb0

* Add Id Message Format

* Add missing types

Co-authored-by: Shadow <william.shadow@outlook.com>

* Format

* Format

* Apply suggestions

* Fix bug

* Apply suggestions

---------

Co-authored-by: Shadow <william.shadow@outlook.com>

This is a bot created issue.

**Comment by Fleny113** [comment]
Issue related to [discord/discord-api-docs](https://github.com/discord/discord-api-docs) can be useful and keeping them is a better idea until they get adressed
