### ISSUE TITLE
Create a Deprecated function that enables all desired props

### ISSUE THREAD

**Issue by Skillz4Killz** [discordeno/discordeno#3154]

**Comment by MatthewSH** [comment]
For context for anyone else coming in, this is stemming from a conversation regarding how to release v19 without the CLI being a blocker but making `desiredProperties` a bit easier to work with in the short term. 

I proposed:
> ```javascript
> export const enableAllProperties = (bot) => {
>   // flip them all here
>   console.log('some notice saying how this is a workaround and should not be relied on')
>}
> ```
> In examples you can use that to help ease people into the concept of desired properties as they transition from other libraries while also giving people the option to opt-into it for benefits.
> — [Discord Message](https://discord.com/channels/785384884197392384/1163894534137204826/1164355876199608400)

----

My thoughts, I don't think it should be deprecated personally. I think `desiredProperties` is a barrier for entry already and telling people they have to run a CLI to even get started with the bot is another potential barrier when trying to appeal to a larger audience. Those features, in my opinion, should not be required to get started.

As an example, with my personal bot on my server I have no need to disable anything at this time and probably will never need to disable anything as it's not even over 10k members yet (8k currently). I will never need to update typings or regenerate anything the CLI is planned for initially so adding that extra step just adds more the development time. Is it that much? No. Is it probably a one time thing? Yes. However, we're having larger conversations in regards to barrier for entry to contribution and development and I think these kind of methods, while not ideal and we should definitely flag them as such, will help with that.
