### ISSUE TITLE
Create a contributing section on the website

### ISSUE THREAD

**Issue by Skillz4Killz** [discordeno/discordeno#3155]
- ~~Remove the contributing file~~ Replace contributing file content with link to website contributing page
- Move content to the website
- Add anymore useful things necessary to the contributing section.

```md
- # Contributing

- This isn't a job! Have fun!

## Code Philosophy

- Similar to how DD supports cross platform runtimes, we also are very flexible in the codebase. Where it makes sense to use Classes they can be used but mostly we prefer using no-class based approach.
```

**Comment by MatthewSH** [comment]
Some things that could be useful for contributing:
- Prerequisites
- Description of the tooling used (this could just be a list with links to websites etc)
  - TypeScript
  - ESLint
  - Yarn monorepo
  - Turborepo
  - etc
- Getting started
  - Clone, setup commands, etc 
  - Maybe provide a development project? Something that is a common pattern to test with?
  - Linking project to monorepo (if applicable)
  - Common development commands (build, linting, etc)

I do have concerns with too much detail and becoming a book, I tend to be detailed anyway. I'm not sure how in depth it's recommended to go. I read things like [Quasar](https://github.com/quasarframework/quasar/blob/dev/CONTRIBUTING.md) and [Laravel](https://laravel.com/docs/10.x/contributions) which are super bare bones. So I don't know. I see there's questions about this stuff but how much do we want to assume people know before contributing?
