### ISSUE TITLE
[Discussion] Add renovate (or something similar)

### ISSUE THREAD

**Issue by MatthewSH** [discordeno/discordeno#3163]
Right now there's nothing to automatically update our dependencies to the latest version. Is there a reason DD doesn't use anything like Renovate? It would require more work up front to get everything up to date and dependencies pinned, but long term you could just have it close it's own PRs once tests pass.

The big risk would be it just flooding PRs if no one keeps it up to date.

**Comment by Fleny113** [comment]
There is GitHub dependabot that *every once in a while* it creates an issue for a dependency bump. 

Maybe it could be configured to run on a cron job / push with its workflow file

**Comment by MatthewSH** [comment]
I'm fine with any of them. I personally use Renovate and know you can configure it however you like, I have no experience with Dependabot.

**Comment by MatthewSH** [comment]
Just noticed that Dependabot only runs for websites? Or it's doing something weird. I can say it's not really doing what I'm opening this issue for though. Something that keeps all packages in the monorepo up to date, etc.

**Comment by Fleny113** [comment]
I think it has something to do with the default config it has when is just enabled in the repo settings

**Comment by itohatweb** [comment]
Dependabot has a configuration. You can read more about Dependabot here: https://docs.github.com/en/code-security/dependabot/dependabot-version-updates

**Comment by MatthewSH** [comment]
Could it also be applied to the monorepo as well to keep the packages up to date there?

**Comment by Fleny113** [comment]
> Could it also be applied to the monorepo as well to keep the packages up to date there?

Dependabot should be able to find the package.json + yarn.lock files in the repo but there are the config to manually set the folder in the config file if i remember correctly

**Comment by H01001000** [comment]
we (me and Skillz) talk about this on 12/01/2022 but forgot why we didn't add it
