### ISSUE TITLE
[Docs]: State the recommended code editor used by developers (if applicable)

### ISSUE THREAD

**Issue by MatthewSH** [discordeno/discordeno#3170]
I don't know what the majority of people use, besides itoh with Helix, but I am under the impression *most* people use VSCode. I know we have VSCode settings as well, it may help new comers to state that we recommend VScode, assuming that we do in fact recommend is as the standard. This can help eliminate questions and help us tailor the documentation to the recommended editor.

**Comment by Fleny113** [comment]
This is actually already in the code for the website, so i will close the issue
![image](https://github.com/discordeno/discordeno/assets/45207244/a5d0ee4c-d97d-40a7-942c-a77b96ba5cc8)
