### ISSUE TITLE
[Docs]: Create a "Testing" section and move that out of getting started

### ISSUE THREAD

**Issue by MatthewSH** [discordeno/discordeno#3171]
I do think it's very important to list the steps for testing, but I think it would be beneficial to create a dedicated testing section to explain the process and how the tests work. For the most part, a new contributor may not need to know about testing when initially diving in until they are developing or closer to time when they want to open a PR. 

While it's good to test as you go, I don't think it's needed in the "first steps" section.

**Comment by rajneesh-18** [comment]
What should I do here to contributing in these no code repo?
