### ISSUE TITLE
[Feat]: Minimum NodeJS version

### ISSUE THREAD

**Issue by MatthewSH** [discordeno/discordeno#3173]
Right now we require minimum Node v14.0.0:
https://github.com/discordeno/discordeno/blob/c460c88a845a7c4e188915b1cb215145719ab2fe/package.json#L40

Node 14 was [EoL in April of this year](https://github.com/nodejs/Release?tab=readme-ov-file#end-of-life-releases). Is there anything tying us to Node 14 or can we look to supporting Node 18 minimum? Maybe even look to upgrading to Node 20 instead? Although Node 18 will be supported 2025 so I'm good with Node 18 (I use Node 18 anyway).

**Comment by Fleny113** [comment]
In fact to use @discordeno/rest you need node 18 as it requires the build-in fetch unless you polyfill

**Comment by MatthewSH** [comment]
So we should probably update the root package then haha

**Comment by H01001000** [comment]
Also need to update the sub package’s one
