### ISSUE TITLE
[Docs]: "Documentation" contribution section

### ISSUE THREAD

**Issue by MatthewSH** [discordeno/discordeno#3176]
It's worth having a dedicated section for those contributors who **just** want to work on making the docs and website better. This section could include contributing from the web only or local development and running the website locally.

**Comment by H01001000** [comment]
maybe also need to add we're using turbo and yarn berry/workspace, thus need yarn >v1 and maybe add some guild on turbo then delete this https://github.com/discordeno/discordeno/blob/main/howToUseTurborepo.md
