### ISSUE TITLE
[Docs]: List the root project scripts

### ISSUE THREAD

**Issue by MatthewSH** [discordeno/discordeno#3179]
Should probably have a dedicated section explaining all the scripts ran and what their intention is.

**Comment by H01001000** [comment]
- build -- build to js (only) with swc
- build:type -- compile the type to .d.ts with tsc
- release-build -- build using above script
- fmt -- format with eslint
- lint -- check style
- test:unit-coverage -- run unit test with mocha and show coverage in stdout and ./coverage
- test:unit -- same as above but not show coverage in stdout but  ./coverage
- test:deno-unit -- run unit test in deno (compile test to js, use /scripts/fixDenoTestExtension.js to make it deno runable, then run with deno test)
- test:unit:watch -- run unit test in watch mode without coverage
- test:integration -- run integration test
- test:type -- check the type of source code
- test:test-type -- check the type of test code

**Comment by MatthewSH** [comment]
>     * fmt -- format with eslint
> 
>     * lint -- check style
Do we need both `fmt` and `lint`? both use ESLint, one just lists the issues and one just fixes them. We also run `lint-staged` on pre-commit so we're forcing a `fmt` run anyway.

**Comment by H01001000** [comment]
I prefer keeping lint. fmt? Idm

**Comment by MatthewSH** [comment]
> I prefer keeping lint. fmt? Idm. It’s easier for ci, and sometimes :) I just force bypass the pre commit, cuz there is style problem from other commit but I don’t want to fix it here

Pre-commit should auto-fix anything staged. Unless there's a project that's messed up (I know website is messed up at the moment).
