### ISSUE TITLE
Add heartbeat latency

### ISSUE THREAD

**Issue by remagnedlogeht** [discordeno/discordeno#319]
It would be like client.ws.ping

**Comment by Skillz4Killz** [comment]
This is something that not many devs really need. I don't think it is worth having this in the core lib especially when it is not required to have a bot function. It would take up memory for each shard for no reason whatsoever for most bots. For most bots a Date.now - message.timestamp is enough.

For the rare few who need this latency it's actually really easy to do yourself.
1. Use the rawGateway event to handle incoming events for heartbeats and ack events.
2. Use the debug event with the `gatewayHeartbeat` type filter and you can tell when a heartbeat is sent.
