### ISSUE TITLE
[CLI] npx discordeno generate

### ISSUE THREAD

**Issue by Skillz4Killz** [discordeno/discordeno#3190]
I've created a basic mockup of how this code should work. Need to finish this up with 1 type before we start implementing for all types. 

Try to see if we can get the Message.id type created.

**Comment by MatthewSH** [comment]
Is the mockup anywhere? Curious to see whatcha thinking.

**Comment by Fleny113** [comment]
In a situation where you only enabled the `Message.id` for example, what should be the state of the other values in the type? I thought about 3 possibile implementation
- Setting the value of the "undesired" propriety to `never`
- Marking it as nullable
- Removing the propriety from the type at all

Setting the value to never or making it as nullable enables to add a comment on them but
- For the `never` you could still pass the value and don't get TS errors if the function is typed with `any`, `unknown`, `never` or with generics that allow `never`
- For the nullable this does still present the issue of the TS errors not being reliable but could also implicitly give an information that is not true: the fact that you _might_ get the value, or it could conflict with values that are actually nullable from the discord docs

While removing them might be even more confusing that it is at the moment where at runtime you don't get the values but you are going to get a TS error about the prop not exiting, but this does pose an additional problem as an empty interface means `NonNullable<unknown>` for Typescript and not an empty object

There is a tradeoff to be made and _i think_ that the `never` for all proprieties (even tho might be the most complex on the implementation lever) could be the best one as the cases where you don't get the TS errors are very specific and one of the cases implies poorly typed functions

*Also, this applies if you don't enable anything at all, so given the message id example, on the channel it would be all never, all nullable or empty*

**Comment by H01001000** [comment]
Or make it as a setting
