### ISSUE TITLE
[api-docs] Update OAuth2.md to clarify application.commands scope (#6324)

### ISSUE THREAD

**Issue by itohatweb** [discordeno/discordeno#3233]
A new commit was made into the api-docs repo: https://github.com/discord/discord-api-docs/commit/ee0af636df12745453236c3a1c9d478b9f02ee11
* Update OAuth2.md

* Update docs/topics/OAuth2.md

---------

Co-authored-by: shay <swdewael@gmail.com>

This is a bot created issue.

**Comment by MatthewSH** [comment]
@Fleny113 do we care about these kind of doc updates? If so I'm down to keep it open.
