### ISSUE TITLE
[Bug]: Rest proxy throwing error with file uploads

### ISSUE THREAD

**Issue by Fleny113** [discordeno/discordeno#3354]
### Runtime

NodeJS

### Runtime Version

21.5.0

### Version

19.0.0-next.d81b28a

### Describe the bug

When uploading a file discord requires that the request is performed with a `multipart/form-data` body and with optionally an `payload_json` field in the form data for the normal json content along the files, the current rest proxy (or `rest-passthrough`) currently errors the moment it receives a `multipart/form-data` body with the following error: `Error: Error: Unsupported Media Type: multipart/form-data; boundary=----formdata-undici-050761408177`

> [!NOTE]
> The node version is specified but does not impact in any way this issue
> also the rest proxy that was implemented before #3269 (`feat!: rewrite proxy app with fastify`) _provably_ had the same issue

#### To reproduce:
1. Run the code for the rest proxy ([/docker-apps/rest-passthrough](https://github.com/discordeno/discordeno/tree/main/docker-apps/rest-passthrough))
1. Use the code in [Code to reproduce the bug](#code-to-reproduce-the-bug)

### What should've happened?

The request does not make `fastify` reject the request with an error caused by the unsupported media type and the files are uploaded to discord along the JSON content attached

### Code to reproduce the bug

```typescript
import { createBot, Intents } from '@discordeno/bot'

const bot = createBot({
  token: process.env.TOKEN,
  events: { 
    async messageCreate(message) {
      if (message.author.bot) return;

      await bot.helpers.sendMessage(message.channelId, { content: "message content", files: [{ name: "test.txt", new Blob(["abc"]) }] })
    }
  },
  intents: Intents.Guilds | Intents.GuildMessages | Intents.MessageContent,
  defaultDesiredPropertiesValue: true,
  rest: {
    authorization: process.AUTHORIZATION_TOKEN,
    baseUrl: "http://localhost:8000",
  }
})

bot.start()
```

**Comment by Fleny113** [comment]
Reported by mk3ext on discord.

Thread link: https://discord.com/channels/785384884197392384/1192866946853638174

**Comment by MatthewSH** [comment]
I will try to review this ASAP, thanks for the bump on this Fleny. Missed it.
