### ISSUE TITLE
Issue with defining an interface within a structure that supports getters

### ISSUE THREAD

**Issue by OSCAR-WOS** [discordeno/discordeno#336]
Structures that include getters have a ``Partial`` reference to the interface, however issue occur when the declare Interface is in the same file, putting it above the imports fails to include additional properties. Currently fix is to seperate into 2 seperate files.

```
error: Uncaught SyntaxError: The requested module '../../deps.ts' does not provide an export named 'Message'
  Message,
~~~~~~~
    at <anonymous> (<file:///C:/Users/user/Documents/Git/instinct-deno/src/structures/1-message.ts#1>:8:1)
```

![image](https://user-images.githubusercontent.com/29248751/103465100-9647f800-4d30-11eb-945f-dee22b9c2294.png)
![image](https://user-images.githubusercontent.com/29248751/103465102-a3fd7d80-4d30-11eb-8c87-0b47f9b627b1.png)

**Comment by OSCAR-WOS** [comment]
Seems to be completely bugging out, one compile time it's fine, another it errors.
![image](https://user-images.githubusercontent.com/29248751/103468593-af61a080-4d52-11eb-87db-585cb51c5bde.png)

**Comment by Skillz4Killz** [comment]
@OSCAR-WOS This is an upstream bug in Deno that due to lack ofmodule augmentation support.

Run your code with`--no-check` until Deno adds support for it.
