### ISSUE TITLE
Add rateLimit to EventHandlers

### ISSUE THREAD

**Issue by MilSci** [discordeno/discordeno#349]
## The function should be executed if your bot is rate limited

Should contain the following parameters:

[object] **rateLimit** - Contains the rate limit info
[number] **rateLimit.timeout** - The timeout in milliseconds
[number] **rateLimit.limit** - Number of requests that can be made to endpoint
[string] **rateLimit.method** - HTTP method used for request
[string] **rateLimit.path** - Path used for request
[string] **rateLimit.route** - Route used for request

[Adapted from Discord.js](https://discord.js.org/#/docs/main/stable/class/Client?scrollTo=e-rateLimit)

* Will most likely need to write an interface for the `rateLimit` object

**Comment by itohatweb** [comment]
If possible please wait until types are finished if everything goes right it should take max 2-3 days now. idk I don't want more merge conflicts than there are now.

**Comment by ayntee** [comment]
It is currently possible using the debug event; however, I think this is not an ideal solution.
```ts
eventHandlers.debug = (data) => {
  if (data.type && data.type !== "requestFetched") return;
  
  const rateLimit = data.response.headers["x-ratelimit-limit"];
  const rateLimitRetryAfter = data.response.headers["x-ratelimit-reset-after"];
};
```
