### ISSUE TITLE
Cache Channel if message is send through a DM channel

### ISSUE THREAD

**Issue by itohatweb** [discordeno/discordeno#357]
Since Discord has removed channel creation events for DM Channel the `sendMessage()` function does not work for DMs anymore. So I suggest we cache the channel in `handleInternalMessageCreate()` controller. This would make `sendDirectMessage()` redundant.

PS: Please don't work on this issue until next branch is merged into master since that would just mean more merge conflicts.

**Comment by Skillz4Killz** [comment]
Not ideal as discussed in discord
