### ISSUE TITLE
[Feat]: Use Flags enums instead of `number` in typings

### ISSUE THREAD

**Issue by Fleny113** [discordeno/discordeno#3612]
### Tell us what problem the feature would solve

Currently in a bunch of places, such as `DiscordUser` we use `number` on the `flags` and `public_flags`. However, discord does document what are the possibile flags, for the user flags (public and not) it is on the [User object user flags](https://discord.com/developers/docs/resources/user#user-object-user-flags)

### Describe the solution you'd like

Use/create the enums for the flags for there values

### Describe alternatives you've considered

Manually use the enum that exists with the exiting `number` type, however this does not guarantee the use of the currenct enum

**Comment by lts20050703** [comment]
We already have ToggleBitfield (reference: https://github.com/discordeno/discordeno/tree/main/packages/bot/src/transformers/toggles), so yeah a flags and public_flags toggles would be nice

**Comment by Fleny113** [comment]
> We already have ToggleBitfield (reference: https://github.com/discordeno/discordeno/tree/main/packages/bot/src/transformers/toggles), so yeah a flags and public_flags toggles would be nice

From what i understand the toggleBitfield are used to avoid having to store a considerable amount of booleans, not for flags. Correct me if i'm wrong

**Comment by lts20050703** [comment]
Oh wait I'm dumb smh

But yeah a enum, something like the Intents enum would be nice

**Comment by lts20050703** [comment]
Wait aren't we already have that? https://github.com/discordeno/discordeno/blob/ad7e74c4cd3f704442acea38dd890018ab0d1f86/packages/types/src/shared.ts#L19

**Comment by Fleny113** [comment]
> Wait aren't we already have that? https://github.com/discordeno/discordeno/blob/ad7e74c4cd3f704442acea38dd890018ab0d1f86/packages/types/src/shared.ts#L19

In some cases we don't use them (user) in some we don't have it (member, idr if we merged that but still)

**Comment by Fleny113** [comment]
We will add the enums, but we will keep the number typing, so this issue can be closed
