### ISSUE TITLE
Add a page for collectors to guide

### ISSUE THREAD

**Issue by ghost** [discordeno/discordeno#372]
A thorough explanation of:
- What are collectors?
- How collectors work?
- Types of collectors
  - Message collectors
  - Reaction collectors
- Appropriate scenarios where collectors are suitable
- An example command utilizing collectors

If you are interested in taking this, please leave a comment.

**Comment by rmobis** [comment]
Is there any place to find this information? Even if not in a proper documentation format, but somewhere I could read some code or conversation regarding it?

**Comment by itohatweb** [comment]
There is no documentation about Collectors. Also Discordeno Collectors are more a boilerplate thing so the code is there: https://github.com/discordeno/boilerplate/blob/master/src/utils/collectors.ts If you have any other questions feel free to join our discord server: https://discord.gg/5vBgXk3UcZ
