### ISSUE TITLE
Remove sendDM() in favor of DMChannel Interface or Channel Interface Extension 

### ISSUE THREAD

**Issue by GarbearSheer** [discordeno/discordeno#374]
Currently, sendDM() requires a user to be cached in order to function. If the user would like to use a command in a DM Channel, the dev must manually cache them or have them be active in a guild chat to get the proper functionality. I am proposing another interface such as one called "DMChannel" or something similar where it has functionality identical to that of the Channel Interface (minus the permission methods and all that other stuff stripped). It is also impossible to use the reply method in DMs as it gives a permission error, even though DM Channels do not have such permission. It would be nice to also move the send method to the channel interface that way we could Channel.send() for both regular channels and DM Channels with the new interface.

**Comment by Skillz4Killz** [comment]
We should reroute sendMessage to dm if its in a dm like

```ts
const channel = await cacheHandlers.get("channels", channelID);
  if (!channel) {
    if (await cacheHandlers.has(channelID)) return sendDirectMessage(channelID, content)
    throw new Error(Errors.CHANNEL_NOT_FOUND);
  }
```

**Comment by itohatweb** [comment]
tbh I don't really like this solution.

**Comment by itohatweb** [comment]
After thinking: Skillz your rerouting solution does not work
