### ISSUE TITLE
Slash commands can not work if the user ID of the bot is not the same as the applications' client ID

### ISSUE THREAD

**Issue by invalidCards** [discordeno/discordeno#435]
I have a somewhat old bot (probably early 2017-ish) that had a problem yesterday that it could not create slash commands. Together with a few members of the Discord we found out that the application was at fault, because creating a brand new one solved the issue.

I've looked into the issue a bit more by cloning `master` and debugging the code locally, and I've found out why it breaks - on this particular bot, the user ID and the application ID are not the same. Discordeno expects these to be the same, and will try to use the user ID for registering the slash command (using the `COMMANDS_GUILD` and `COMMANDS` endpoints defined in `src/util/constants.ts`), which obviously fails.

The solution here *should* be to register both the bot ID and the application ID in the `handleInternalReady` handler (`/src/api/controllers/misc.ts`), and using the latter for slash command-related functionality.

**Comment by itohatweb** [comment]
We've found a solution. I'll make a PR after https://github.com/discordeno/discordeno/pull/428 is merged.
