### ISSUE TITLE
Remove Object Arguments in Functions

### ISSUE THREAD

**Issue by itohatweb** [discordeno/discordeno#454]
There are some functions that take an object as argument but majority of functions don't. For consistency that functions should take eg. an ID as argument too.

**Comment by ayntee** [comment]
The maximum number of individual parameters that a function should accommodate is 4, exceeding this limit, the parameters should be converted into an object.

**Comment by ayntee** [comment]
> There are some functions that take an object as argument but majority of functions don't. For consistency that functions should take eg. an ID as argument too.

Can you provide a list of functions having object as parameter with minimal parameters as properties?

**Comment by itohatweb** [comment]
I don't have a full list but eg:
- guildIconURL
- guildSplashURL
- guildBannerURL
- createGuildChannel
- requestAllMembers
