### ISSUE TITLE
Better name for executeSlashCommand

### ISSUE THREAD

**Issue by itohatweb** [discordeno/discordeno#455]
Imo `executeSlashCommand` is a bad name and other functions are named eg. `deleteSlashResponse`. So imo we should find a better name for that.

**Comment by ayntee** [comment]
I would recommend following API documentation to rename it.

**Comment by itohatweb** [comment]
APIs convention would be `createInteractionResponse` and that does not fit into our name scheme.

**Comment by ayntee** [comment]
Thoughts? @Skillz4Killz

**Comment by ayntee** [comment]
> APIs convention would be `createInteractionResponse` and that does not fit into our name scheme.

Wait we have a naming scheme? :joy:

**Comment by itohatweb** [comment]
Not really but in this case all your function use `slashCommand` instead of `Interaction`

**Comment by itohatweb** [comment]
Thinking of we could use `createSlashResponse`

**Comment by Skillz4Killz** [comment]
I would prefer something like `sendXXXX` since we have `sendMessage`, `sendDirectMessage` and so on even in boilerplate we have `sendEmbed`, `sendResponse` etc...

**Comment by ayntee** [comment]
> I would prefer something like `sendXXXX` since we have `sendMessage`, `sendDirectMessage` and so on even in boilerplate we have `sendEmbed`, `sendResponse` etc...

+1
