### ISSUE TITLE
Resolve RequestManager using await before returning the value

### ISSUE THREAD

**Issue by itohatweb** [discordeno/discordeno#465]
As weird bugs can occur when RequestManager gets returned, the result should be cached in a variable and then that variable should be returned.

**Comment by ayntee** [comment]
Can you provide more details in the description of the PR like what are instances where said issue is occurring, etc?

**Comment by itohatweb** [comment]
This originally was requested by Skillz. According to him annoying bugs occur and the added await helps stack trace issues.
