### ISSUE TITLE
cache: oldValue, newValue don't work because of reference

### ISSUE THREAD

**Issue by itohatweb** [discordeno/discordeno#475]
Since cacheHandlers returns eg `cache.get()` things like oldValue, newValue don't work cause of reference.

eg:
```ts
const payload = data.d as IDK;
const oldValue = await cacheHandlers.get("something", ID);

await cacheHandlers.set("something", ID, payload);
const newValue = await cacheHandlers.get("something", ID);

oldValue === newValue // true
```

Hope explanation isn't so bad.

**Comment by itohatweb** [comment]
I already have a work around for that so I would do that.

**Comment by itohatweb** [comment]
Hmm now I tested it with more functions and got a different result. Means not all events work the same way in that regards.

**Comment by ayntee** [comment]
> Since cacheHandlers returns eg `cache.get()` things like oldValue, newValue don't work cause of reference.
> 
> eg:
> 
> ```ts
> const payload = data.d as IDK;
> const oldValue = await cacheHandlers.get("something", ID);
> 
> await cacheHandlers.set("something", ID, payload);
> const newValue = await cacheHandlers.get("something", ID);
> 
> oldValue === newValue // true
> ```
> 
> Hope explanation isn't so bad.

Examples of such events?
