### ISSUE TITLE
slowmode -> rateLimitPerUser

### ISSUE THREAD

**Issue by ayntee** [discordeno/discordeno#476]
Replace all instances and occurrences of `slowmode` with `rateLimitPerUser`, as previously discussed. Now you might have a question, why is this necessary?

This change is proposed to mainly avoid confusion between the library and the API. Additionally, we should be consistent with the API and try to follow their spec wherever we can as well as with our code. Besides, majority of Discordeno users migrate from Discord.js which uses `rateLimitPerUser`. Feel free to leave your thoughts in the comments.

**Comment by itohatweb** [comment]
On it. Will be implemented in types branch.

**Comment by Skillz4Killz** [comment]
The best reasoning imo is so it can easily be used with the snake => camel and vice versa
