### ISSUE TITLE
Incorrect "user" field in GuildTemplate interface

### ISSUE THREAD

**Issue by ayntee** [discordeno/discordeno#500]
The `GuildTemplate` interface contains an incorrect field "user" inside it; it should be removed and replaced with "creator" which the correct field.
PS: must be a typo while writing the type for "GuildTemplate". Make sure to comment on this issue before opening a PR.

**Comment by pawanakhil** [comment]
Would like to work on this.

**Comment by itohatweb** [comment]
This issue is unnecessary and should be closed. This is already coverd in the types issue.
