### ISSUE TITLE
Discordeno doesn't omit message content for any InteractionResponseType

### ISSUE THREAD

**Issue by GarbearSheer** [discordeno/discordeno#503]
Discordeno doesn't seem to be omitting message content in slash commands using any InteractionResponseType.

InteractionResponseType.ACKNOWLEDGE is supposed to eat user input and not send a message, however, only the former works as intended.

InteractionResponseType.ACK_WITH_SOURCE is supposed to display user input and not send a message, however, only the former works as intended again.

This can be easily tested using this code:

```typescript
executeSlashCommand(payload.id, payload.token, {
  type: InteractionResponseType.ACKNOWLEDGE,
  data: {
    content: "Shouldn't see this."
  }
});
```

**Comment by ayntee** [comment]
The interaction response type `Acknowledge` is deprecated; closing this
