### ISSUE TITLE
Missing annotation and/or documentation for file attachments

### ISSUE THREAD

**Issue by MKuranowski** [discordeno/discordeno#506]
The current documentation describes MessageContent.file.blob as `unknown`, which is absolutely useless. The website <https://discordeno.mod.land/> also doesn't contain any documentation on how to add attachments to a message.

Including something like `file: {blob: Deno.readFileSync("some_file.whatever"), name: "some_file.whatever"}` in MessageContent causes a `The request was improperly formatted, or the server couldn't understand it.` error.

Since the option exists, I'm sure there's a particular type that this function accepts so that file attachments work, but, the lack of documentation means I have no way o figuring this argument out.

So, what should be the type of `MessageContent.file.blob`? And why isn't this type described in the MessageContent description?

**Comment by DjDeveloperr** [comment]
Yup the type is weird - try using `blob: new Blob([Deno.readFileSync("some_file.whatever")])`

**Comment by itohatweb** [comment]
`file: {blob: Deno.readFileSync("some_file.whatever"), name: "some_file.whatever"}` does not work because you are doing it wrong. You are reading the file bot not converting it to a Blob.
Ayntees example:
```ts
const bytes = Deno.readFileSync("./jerry.jpeg"");
message.send({
  file: {
    blob: new Blob([bytes]),
    name: "some_file.whatever",
  }
});
```

**Comment by itohatweb** [comment]
> So, what should be the type of MessageContent.file.blob? And why isn't this type described in the MessageContent description?
We already had better types but since it was breaking we reverted the change. Most likely this will be added in v11

**Comment by MKuranowski** [comment]
Ok, cool, so then why isn't the type of `MessageContent.file.blob` set to `Blob`?
