### ISSUE TITLE
Replace recursive functions with while loops

### ISSUE THREAD

**Issue by itohatweb** [discordeno/discordeno#539]
Rn v8 does not have proper handling for recursive functions so suddenly we will hit a max call stack size exceeded error because of that we should replace them with while loops for now.

**Comment by ayntee** [comment]
"you shouldn't have an issue with stack when using recursive functions
well I guess I am wrong"

**Comment by itohatweb** [comment]
naaaa

**Comment by itohatweb** [comment]
you got my message wrong here

**Comment by Skillz4Killz** [comment]
I think its safe to close this now
