### ISSUE TITLE
Response status checking for readable errors will never be true

### ISSUE THREAD

**Issue by A5rocks** [discordeno/discordeno#546]
Relevant code: https://github.com/discordeno/discordeno/blob/997189ec4af56a362c6460471d808a7ad9c2a574/src/rest/queue.ts#L65

I believe this should be a `||` (though `< 200` does not feel necessary, given 1xx http codes are not *technically* an error).

**Comment by itohatweb** [comment]
Pls don't just add an `||` this will break code. I'll look more into it tomorrow.

**Comment by itohatweb** [comment]
> Pls don't just add an `||` this will break code. I'll look more into it tomorrow.

Ok I take back my comment I was pretty tired whilst writing it and I confused the `<` and `>`. I'm sorry if I confused you.
