### ISSUE TITLE
Slash Command Name Regex

### ISSUE THREAD

**Issue by Skillz4Killz** [discordeno/discordeno#567]
The `name` of a slash command should be checked using the regex that is documented.

https://github.com/discord/discord-api-docs/commit/668a990efe8b1e22c2cbd29ef73c2ac7d95f7234

NEW: https://github.com/discord/discord-api-docs/commit/df59cef52e162c4d225c81c76e7e022206027cfc

3-32 character name matching `^(?:\w|[-_])+$`

**Comment by ayntee** [comment]
I assume the name is to be checked during the creation of a slash command (createSlashCommand function) and nowhere else?

**Comment by itohatweb** [comment]
No `upsertSlashCommand` and `upsertSlashCommands` need it too

**Comment by Skillz4Killz** [comment]
Anywhere it is being used for example what itoh sent

Also note this limit was later changed from min of 3 to min of 1 so use `1`
