### ISSUE TITLE
Slash Limits Changes

### ISSUE THREAD

**Issue by Skillz4Killz** [discordeno/discordeno#584]
An app can have up to 100 top-level global commands with unique names
- An app can have up to an additional 100 guild commands per guild
- An app can have up to 25 subcommand groups on a top-level command
- An app can have up to 25 subcommands within a subcommand group
- commands can have up to 25 `options`
- options can have up to 25 `choices`
- Maximum of 4000 characters for combined name, description, and value properties for each command and its subcommands and groups

- Global rate limit of 200 application command creates per day per guild

- Choices `value` prop if it is a string can not be more than 100 characters

**Comment by Skillz4Killz** [comment]
- 200 global command creates per day
- A command is created when a command by that name doesn't already exist within its scope.  So it will count toward the limit only if the command doesn't already exist.  PUT can count toward the limit multiple times if you create new commands that don't match the name of a previous command.

**Comment by itohatweb** [comment]
`Maximum of 4000 characters` does this mean I could create a command with its name being eg 1000 characters long?

**Comment by ayntee** [comment]
> `Maximum of 4000 characters` does this mean I could create a command with its name being eg 1000 characters long?

No, the name is limited to 32 characters, and the description is limited to 100 characters...
