### ISSUE TITLE
Add "deaf" and "mute" on the guild member update event

### ISSUE THREAD

**Issue by itohatweb** [discordeno/discordeno#585]
# NOT CONFIRMED (NEITHER MERGED) YET

Pending: https://github.com/discord/discord-api-docs/pull/2549

**Comment by itohatweb** [comment]
Actually I tested this now and I don't receive a guild member update event on mute/deafen. But I'll leave this issue open until discord/discord-api-docs#2549 is being merged/closed

**Comment by ayntee** [comment]
Feel free to reopen once the corresponding PR is merged
