### ISSUE TITLE
Add `rawGuildIconURL`, `rawGuildSplashURL` and `rawGuildBannerURL`

### ISSUE THREAD

**Issue by itohatweb** [discordeno/discordeno#633]
In case you want to get the icons from an uncached guild. We do the same for `avatarURL`

**Comment by ayntee** [comment]
I think we should just add an option "raw" to makeAvatarURL function

**Comment by itohatweb** [comment]
Then we would need to change the args too. Rn we are requiring the guild object for these funcitons.

**Comment by Skillz4Killz** [comment]
By default these functions should use the `raw` version as in the ids, it should not have 2 functions. The cached version should be just a getter.
