### ISSUE TITLE
Rename `cache` to bot

### ISSUE THREAD

**Issue by Skillz4Killz** [discordeno/discordeno#659]
I believe it would be worth renaming cache to `bot`. A lot of people write code doing `bot.guilds` and when they see `cache.guilds` its not evident nor is it clear what cache is to beginners. `bot` would make that clear. 

On a sidenote: i've seen some users just say they dont like DD because it uses cache.guilds since they have a bad taste/opinion from another library that uses that style so it would also help resolve that

**Comment by ayntee** [comment]
I don't know but `bot` is very ambiguous; not to mention, it looks like there is main object "bot" (similar to `new Client()`)

**Comment by Skillz4Killz** [comment]
> `bot` is very ambiguous compared to `cache`, which is quite self-explanatory; not to mention, this change promotes the presence of a main object "bot" (similar to `new Client()`), Discordeno however should divert from that behavior. It will do the opposite effect, it will make it ambiguous and vague.

I believe it is the best linguistic wise. When a developer is thinking okay so how do i get all the guilds on my bot the code is essentially `bot.guilds`. You don't really think in terms of `cache`. That is a bit advanced topic that i think most beginners will not understand. I don't think it promotes a main object, just renames it. It's still the same thing. I do agree we should avoid the God object at all costs, but is a name going to effect that?

> Discordeno is very different within basic design, renaming `cache` to `bot` still will not solve the issue of fundamental design difference between other Node.js libraries and Discordeno

No i think, the design issue became mute since v10. To an end user, there is basically no difference. With the getters, it provides nearly the same exact experience. It is the developers of the library itself, who have the different experience becuase of the design.

Renaming the cache to bot isn't intended to change the design but the problem where some users hate the concept of `cache.x` because of their usage in other libs.

**Comment by ayntee** [comment]
> Is it just me but I kinda like `cache`.

+1 for cache
