### ISSUE TITLE
Guild Create handler does not cache Guild Members

### ISSUE THREAD

**Issue by itohatweb** [discordeno/discordeno#661]
**Is your feature request related to a problem? Please describe.** 
Rn guild create handler does not cache members itsn't so a big problem that we are not caching them so what do you guys think?

**Describe the solution you'd like** Cache the members

**Describe alternatives you've considered** Don't cache the members cause it is not really necessary but idk

**Comment by ayntee** [comment]
@Skillz4Killz

**Comment by Skillz4Killz** [comment]
We need to fix this
