### ISSUE TITLE
Structures CreateGuild should cache the bot member

### ISSUE THREAD

**Issue by itohatweb** [discordeno/discordeno#663]
**Describe the bug**
Rn `createGuildStruct` does not cache the Bot this can lead to some permission checking bugs.

**To Reproduce** Steps to reproduce the behavior:

1. Add the bot to a new guild
2. Do some perm checking

**Comment by ayntee** [comment]
Can you explain what is wrong currently in depth?

**Comment by itohatweb** [comment]
When the bot isn't cached on guild create, the roles of the bot aren't cached. So permission checking does not work properly.

**Comment by itohatweb** [comment]
The bot should be cached directly on guild create because creating all the member structures can take a bit of time.
