### ISSUE TITLE
Collection.prototype.first() may return undefined

### ISSUE THREAD

**Issue by ayntee** [discordeno/discordeno#679]
**Describe the bug**
If the collection is empty, that is, contains zero elements, collection.first() will return undefined as the value.

**Expected behavior**
The type for .first() is `V` or the value, however, it may return undefined as previously mentioned.

**Version details (please complete the following information):**

- Discordeno version: 10.5.0
- Deno version: 1.8.0

**Comment by itohatweb** [comment]
The same for `last` and `random`
