### ISSUE TITLE
Add a function to clone a channel

### ISSUE THREAD

**Issue by Myssiry** [discordeno/discordeno#761]
**Is your feature request related to a problem?**
Currently there is not a way to clone a channel in this library.

**Describe the solution you'd like**
Add a function which can clone  a channel.

**Describe alternatives you've considered**
There is not any alternative.

**Additional context**
You can look at discord.js documentation for an example of what it should probably do.
(The link is a search, because it differs between different types of channels(voice, text....))
https://discord.js.org/#/docs/main/master/search?q=clone

**Comment by existentiality** [comment]
I'll start working on this.

**Comment by existentiality** [comment]
I've found that because this function "proxies" the create channel function instead of directly accessing APIs, there might be some limitations on how it can be implemented. I would like to try to discuss possible implementation methods before proceeding to continue working on it.

**Comment by ayntee** [comment]
> I've found that because this function "proxies" the create channel function instead of directly accessing APIs, there might be some limitations on how it can be implemented. I would like to try to discuss possible implementations before proceeding to continue working on it.

Essentially, the function should just "collect" existing channel's data and send an HTTP request to create a new channel with the collected data. It should be simple and straight-forward. I am interested to hear your approach, do let me know what you have in mind.

**Comment by existentiality** [comment]
I was more confused about the method of collecting that data. I mostly forgot that `cache` existed and it looks more clear to me now after thinking about it.
