### ISSUE TITLE
Improve directory structure

### ISSUE THREAD

**Issue by itohatweb** [discordeno/discordeno#864]
I'm not 100% confident with our current directory structure it needs to be improved.

Edit: I want to finish everything else before this issue. Rn we still change much and after we are finished its the best do finish the directory structure.

**Comment by Skillz4Killz** [comment]
I don't want to be changing this after v11 so please make sure u decide on a final version before we finish v11(which is still far away)

**Comment by Skillz4Killz** [comment]
Finalizing v11 so re-open if you have a complete concept for this plz

**Comment by itohatweb** [comment]
I want this to be the last issue to be worked on for v11 cause prs will get merge conflicts again etc.

**Comment by Skillz4Killz** [comment]
But you gotta explain what changes need to be made exactly

**Comment by itohatweb** [comment]
I just want to move files around to the corresponding folders, to stick to the 15 files / folder limit.

**Comment by Skillz4Killz** [comment]
Ahh sounds good!
