### ISSUE TITLE
createDiscordenoMember should take member optional

### ISSUE THREAD

**Issue by itohatweb** [discordeno/discordeno#873]
I am thinking of sth like this: `createDiscordenoMember(user, member, guildId)`. This change would make it possible to cache users even if they are not in a guild useful when using direct messages.

What do you guys think of it?

**Comment by Skillz4Killz** [comment]
Need more details

**Comment by Skillz4Killz** [comment]
Itoh u gotta give more details, this doesnt clarify anything

**Comment by itohatweb** [comment]
I'm not sure what details you need. I just want to convert the `createDiscordenoMember(member, guildId)` to `createDiscordenoMember(user, { member?, guildId? })`

**Comment by Skillz4Killz** [comment]
> I am thinking of sth like this: `createDiscordenoMember(user, member, guildId)`. This change would make it possible to cache users even if they are not in a guild useful when using direct messages.
> 
> What do you guys think of it?

You can not dm a user whom you do not share a guild with so i dont understand and need more details why this is necessary

**Comment by itohatweb** [comment]
Discordeno members basically are discord users with getters. We create a new member when we get a `MESSAGE_CREATE` event. When the message is a dm we can't create the member. If we change it like this we can.

**Comment by Skillz4Killz** [comment]
You can not dm a bot you don't share a guild with. A bot can not dm u if u dont share a guild
