### ISSUE TITLE
function to disconnect bot

### ISSUE THREAD

**Issue by x4m3** [discordeno/discordeno#874]
It would be nice if there would be a way to disconnect the bot when you are done with it.

Why would that be useful: I am writing a script to send files with discord via a bot, so I do not want to have the bot online all the time,

Currently the only way to disconnect the bot is to exit the deno script with the `Deno.exit()` method.

thank you!

**Comment by Skillz4Killz** [comment]
Have you considered using webhooks for this? Sounds like you may not need a bot at all

**Comment by Skillz4Killz** [comment]
You can also try doing what we do in tests https://github.com/discordeno/discordeno/blob/main/tests/ws/ws_close.ts#L10

If you still need something please reopen the issue
