### ISSUE TITLE
Enable more slash command option types

### ISSUE THREAD

**Issue by GitHubJasper** [discordeno/discordeno#896]
I would like to use more option types when using slash commands, like `USER`, `CHANNEL`, `ROLE`, etc.
Seems like currently only `STRING` and `INTEGER` are supported, others throw an `INVALID_SLASH_OPTIONS_CHOICES` error.

```
  SUB_COMMAND = 1,
  SUB_COMMAND_GROUP = 2,
  STRING = 3,
  INTEGER = 4,
  BOOLEAN = 5,
  USER = 6,
  CHANNEL = 7,
  ROLE = 8,
```

Maybe this is considered for discordeno 11, but I didn't see it mentioned anywhere.

**Comment by itohatweb** [comment]
This is already implemented in v11
