### ISSUE TITLE
[v11] CreateWebhook avatar should be optional

### ISSUE THREAD

**Issue by Skillz4Killz** [discordeno/discordeno#967]
export interface CreateWebhook {
  /** Name of the webhook (1-80 characters) */
  name: string;
  /** Image for the default webhook avatar */
  avatar: string | null;
}

**Comment by itohatweb** [comment]
are you sure, according to docs it is not optional

**Comment by Skillz4Killz** [comment]
Yes, im sure we pass it to discord as undefined even now but require the user to pass null doesnt make sense
